// dom.js - Geänderte Version

// Wir deklarieren die Variablen hier nur mit 'let', anstatt sie sofort zuzuweisen.
// Das verhindert das Timing-Problem, da die Zuweisung erst später erfolgt.
export let wortgruppenSelectorContainerEl,
    trainerMainViewEl,
    wortgruppenButtonsEl,
    backToWortgruppenButton,
    currentWortgruppeTitleEl,
    modeSelectorEl,
    landAdjColumnEl,
    cardEl,
    questionDisplayEl,
    exampleSentenceDisplayEl,
    taskPromptAreaEl,
    mcUiEl,
    mcAnswersContainerEl,
    spellingModeUiEl,
    singleInputContainerEl,
    spellingInputSingleEl,
    nounInputContainerEl,
    spellingInputNoun1El,
    spellingInputNoun2El,
    checkSpellingButton,
    clozeUiEl,
    clozeHintContainerEl,
    clozeSentenceContainerEl,
    checkClozeButton,
    sentenceUiEl,
    sentenceWordInputContainerEl,
    checkSentenceButton,
    feedbackContainerEl,
    continueButton,
    statsContainerEl,
    correctInRoundEl,
    attemptedInRoundEl,
    accuracyBarEl,
    categoryStatsContainerEl,
    messageBoxEl,
    wordLineContainerEl,
    sentenceLineContainerEl,
    audioWordButtonEl,
    audioSentenceButtonEl,
    SVG_SPEAKER_ICON;