[build]
  # Da der Thementrainer alle Dateien im Root hat, brauchen wir keinen speziellen Build-Befehl
  publish = "."

[build.environment]
  NODE_VERSION = "18"

# Sicherheits-Header für alle Seiten und Ressourcen
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Wichtig für Single Page Apps
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
