[build]
  # Themen-Trainer Dateien ins Root kopieren für standalone Version
  command = "mkdir -p dist && cp packages/trainer-themen/index.html dist/ && cp packages/trainer-themen/*.js dist/ && cp packages/trainer-themen/manifest.json dist/ && cp -r shared dist/"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"