[build]
  # Dieser Befehl kopiert alle benötigten Dateien in ein dist Verzeichnis
  command = """
  mkdir -p dist && \
  cp packages/trainer-basis/index.html \
     packages/trainer-basis/trainer.js \
     packages/trainer-basis/vokabular.js \
     packages/trainer-basis/firebase-config.js \
     packages/trainer-basis/firebase-sync.js \
     packages/trainer-basis/device-sync-ui.js \
     dist/ && \
  mkdir -p dist/shared && \
  cp shared/helfer.js \
     shared/ui-modes.js \
     shared/style.css \
     dist/shared/ && \
  cp LICENSE.md dist/
  """

  # Veröffentliche das dist Verzeichnis
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/LICENSE.md"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"