[build]
  # Vite-Build für TypeScript-Projekt
  command = "npm run build"
  publish = "dist"

[functions]
  external_node_modules = ["@google-cloud/text-to-speech"]

[build.environment]
  NODE_VERSION = "20.19.3"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_CONFIG_PACKAGE_MANAGER = "npm"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://*.googleapis.com https://*.gstatic.com https://*.firebaseapp.com https://*.firebaseio.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.googleapis.com https://apis.google.com https://*.gstatic.com https://*.firebaseapp.com https://cdn.tailwindcss.com; style-src 'self' 'unsafe-inline' https://*.googleapis.com https://fonts.googleapis.com https://cdn.tailwindcss.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://*.googleapis.com https://*.firebaseio.com https://*.firebaseapp.com wss://*.firebaseio.com https://identitytoolkit.googleapis.com; media-src 'self' data: blob: https:"
    Content-Security-Policy = "connect-src 'self' https://ezjihsafleestqanpgdc.supabase.co;"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200