# Haupt-Build-Konfiguration
[build]
  # Da es keine Build-Schritte gibt (nur statische Dateien), kann der Befehl leer bleiben.
  command = ""
  # Das Veröffentlichungsverzeichnis ist das Stammverzeichnis ("root") des Repositories.
  publish = "/" 

# Umgebungsvariablen für den Build-Prozess
[build.environment]
  NODE_VERSION = "18"

# Sicherheits-Header für alle Seiten und Ressourcen
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Spezifischer Header für die LICENSE.md-Datei, um sie korrekt als Textdatei auszuliefern
[[headers]]
  for = "/LICENSE.md"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"
