[build]
  # Dieser Befehl kopiert jetzt ALLE benötigten Dateien.
  command = "mkdir -p dist/shared && cp packages/trainer-basis/*.js packages/trainer-basis/*.html packages/trainer-basis/*.json dist/ && cp shared/*.js shared/*.css dist/shared/"

  # Das Veröffentlichungs-Verzeichnis bleibt dasselbe.
  publish = "dist"