[build]
  # Dieser Befehl ist jetzt explizit und listet jede Datei einzeln auf,
  # um Fehler durch nicht gefundene Platzhalter zu vermeiden.
  # Die `\` am Ende jeder Zeile verbinden alles zu einem einzigen Befehl.
  # Dieser Befehl hat jetzt den KORREKTEN Pfad zur manifest.json.
  command = """
  mkdir -p dist && \
  cp packages/trainer-basis/index.html \
     packages/trainer-basis/trainer.js \
     packages/trainer-basis/vokabular.js \
     packages/trainer-themen/manifest.json \
     dist/ && \
  cp -r shared dist/
  """

  # Das Veröffentlichungs-Verzeichnis bleibt dasselbe.
  publish = "dist"