[build]
  # Dieser Befehl installiert Dependencies UND kopiert Dateien
  command = """
  npm install && \
  mkdir -p dist && \
  cp packages/trainer-basis/index.html \
     packages/trainer-basis/trainer.js \
     packages/trainer-basis/vokabular.js \
     packages/trainer-basis/firebase-config.js \
     packages/trainer-basis/firebase-sync.js \
     packages/trainer-basis/device-sync-ui.js \
     dist/ && \
  cp -r shared dist/ && \
  cp LICENSE.md dist/
  """
  
  # Veröffentliche das dist Verzeichnis
  publish = "dist"
  
  # Functions Directory (im Root, nicht in dist)
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/LICENSE.md"
  [headers.values]
    Content-Type = "text/plain; charset=utf-8"