// packages/trainer-themen/vokabular_kommunikationsmittel.js

export const vokabularKommunikationsmittel = {
    "Kommunikationsmittel": {

        // --- NEUE KATEGORIE 1: Schriftliche Kommunikation ---
        "Schriftliche Kommunikation": [
            {
                id: "kommunikation-schriftlich-001",
                wortart: "Nomen",
                german: "Mail",
                artikel: "die",
                plural: "Mails",
                english: "email",
                example_de: [{ "text": "Danke", "kasus": "none" }, { "text": " ", "kasus": "none" }, { "text": "für", "kasus": "none" }, { "text": " ", "kasus": "none" }, { "text": "deine Mail", "kasus": "akkusativ" }, { "text": ".", "kasus": "none" }],
                example_en: "Thank you for your email.",
                cloze_parts: ["Danke für deine ", "."],
                cloze_answers: ["Mail"]
            },
            {
                id: "kommunikation-schriftlich-002",
                wortart: "Verb",
                german: "mailen",
                english: "to email",
                trennbar: false,
                hilfsverb_perfekt: "haben",
                partizip_ii: "gemailt",
                konjugation_praesens: { ich: "maile", du: "mailst", er_sie_es: "mailt", wir: "mailen", ihr: "mailt", sie_Sie: "mailen" },
                imperativ: { du: "Mail!", ihr: "Mailt!" },
                example_de: [{ "text": "Ich", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "maile", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "dir", "kasus": "dativ" }, { "text": " ", "kasus": "none" }, { "text": "die Fotos", "kasus": "akkusativ" }, { "text": " ", "kasus": "none" }, { "text": "morgen", "kasus": "none" }, { "text": ".", "kasus": "none" }],
                example_en: "I will email you the photos tomorrow.",
                cloze_parts: ["Ich ", " dir die Fotos morgen."],
                cloze_answers: ["maile"]
            },
            {
                id: "kommunikation-schriftlich-003",
                wortart: "Nomen",
                german: "Mailbox",
                artikel: "die",
                plural: "Mailboxen",
                english: "mailbox",
                example_de: [{ "text": "In", "kasus": "none" }, { "text": " ", "kasus": "none" }, { "text": "meiner Mailbox", "kasus": "dativ" }, { "text": " ", "kasus": "none" }, { "text": "sind", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "drei neue Nachrichten", "kasus": "nominativ" }, { "text": ".", "kasus": "none" }],
                example_en: "There are three new messages in my mailbox.",
                cloze_parts: ["In meiner ", " sind drei neue Nachrichten."],
                cloze_answers: ["Mailbox"]
            },
            {
                id: "kommunikation-schriftlich-004",
                wortart: "Nomen",
                german: "Brief",
                artikel: "der",
                plural: "Briefe",
                english: "letter",
                example_de: [{ "text": "Sie", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "bekommt", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "immer", "kasus": "none" }, { "text": " ", "kasus": "none" }, { "text": "viele Briefe", "kasus": "akkusativ" }, { "text": ".", "kasus": "none" }],
                example_en: "She always receives many letters.",
                cloze_parts: ["Sie bekommt immer viele ", "."],
                cloze_answers: ["Briefe"]
            },
            {
                id: "kommunikation-schriftlich-005",
                wortart: "Nomen",
                german: "Postkarte",
                artikel: "die",
                plural: "Postkarten",
                english: "postcard",
                example_de: [{ "text": "Wir", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "schreiben", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "ihm", "kasus": "dativ" }, { "text": " ", "kasus": "none" }, { "text": "eine Postkarte", "kasus": "akkusativ" }, { "text": ".", "kasus": "none" }],
                example_en: "We are writing him a postcard.",
                cloze_parts: ["Wir schreiben ihm eine ", "."],
                cloze_answers: ["Postkarte"]
            },
            {
                id: "kommunikation-schriftlich-006",
                wortart: "Nomen",
                german: "Nachricht",
                artikel: "die",
                plural: "Nachrichten",
                english: "message",
                example_de: [{ "text": "Du", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "hörst", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "die Nachricht", "kasus": "akkusativ" }, { "text": " ", "kasus": "none" }, { "text": "noch einmal", "kasus": "none" }, { "text": ".", "kasus": "none" }],
                example_en: "You hear the message once more.",
                cloze_parts: ["Du hörst die ", " noch einmal."],
                cloze_answers: ["Nachricht"]
            }
        ],

        // --- NEUE KATEGORIE 2: Telefon ---
        "Telefon": [
            {
                id: "kommunikation-telefon-001",
                wortart: "Nomen",
                german: "Handy",
                artikel: "das",
                plural: "Handys",
                english: "mobile phone",
                example_de: [{ "text": "Du", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "kannst", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "mit dem Handy", "kasus": "dativ" }, { "text": " ", "kasus": "none" }, { "text": "telefonieren", "kasus": "verb" }, { "text": ".", "kasus": "none" }],
                example_en: "You can make phone calls with the mobile phone.",
                cloze_parts: ["Du kannst mit dem ", " telefonieren."],
                cloze_answers: ["Handy"]
            },
            {
                id: "kommunikation-telefon-002",
                wortart: "Nomen",
                german: "Telefon",
                artikel: "das",
                plural: "Telefone",
                english: "telephone",
                example_de: [{ "text": "Das Telefon", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "klingelt", "kasus": "verb" }, { "text": ".", "kasus": "none" }],
                example_en: "The telephone is ringing.",
                cloze_parts: ["Das ", " klingelt."],
                cloze_answers: ["Telefon"]
            },
            {
                id: "kommunikation-telefon-003",
                wortart: "Verb",
                german: "telefonieren",
                english: "to make a phone call",
                trennbar: false,
                hilfsverb_perfekt: "haben",
                partizip_ii: "telefoniert",
                konjugation_praesens: { ich: "telefoniere", du: "telefonierst", er_sie_es: "telefoniert", wir: "telefonieren", ihr: "telefoniert", sie_Sie: "telefonieren" },
                imperativ: { du: "Telefonier!", ihr: "Telefoniert!" },
                example_de: [{ "text": "Ich", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "telefoniere", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "oft", "kasus": "none" }, { "text": " ", "kasus": "none" }, { "text": "mit meiner Freundin", "kasus": "dativ" }, { "text": " ", "kasus": "none" }, { "text": "in Frankfurt", "kasus": "dativ" }, { "text": ".", "kasus": "none" }],
                example_en: "I often make phone calls with my friend in Frankfurt.",
                cloze_parts: ["Ich ", " oft mit meiner Freundin in Frankfurt."],
                cloze_answers: ["telefoniere"]
            },
            {
                id: "kommunikation-telefon-004",
                wortart: "Verb",
                german: "anrufen",
                english: "to call",
                trennbar: true,
                hilfsverb_perfekt: "haben",
                partizip_ii: "angerufen",
                konjugation_praesens: { ich: "rufe an", du: "rufst an", er_sie_es: "ruft an", wir: "rufen an", ihr: "ruft an", sie_Sie: "rufen an" },
                imperativ: { du: "Ruf an!", ihr: "Ruft an!" },
                example_de: [{ "text": "Ich", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "rufe", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "dich", "kasus": "akkusativ" }, { "text": " ", "kasus": "none" }, { "text": "morgen", "kasus": "none" }, { "text": " ", "kasus": "none" }, { "text": "an", "kasus": "verb" }, { "text": ".", "kasus": "none" }],
                example_en: "I will call you tomorrow.",
                cloze_parts: ["Ich ", " dich morgen ", "."],
                cloze_answers: ["rufe", "an"]
            },
            {
                id: "kommunikation-telefon-005",
                wortart: "Nomen",
                german: "Anruf",
                artikel: "der",
                plural: "Anrufe",
                english: "call",
                example_de: [{ "text": "Ich", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "warte", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "dann", "kasus": "none" }, { "text": " ", "kasus": "none" }, { "text": "auf", "kasus": "none" }, { "text": " ", "kasus": "none" }, { "text": "deinen Anruf", "kasus": "akkusativ" }, { "text": " ", "kasus": "none" }, { "text": "- okay?", "kasus": "none" }],
                example_en: "I'll wait for your call then - okay?",
                cloze_parts: ["Ich warte dann auf deinen ", " - okay?"],
                cloze_answers: ["Anruf"]
            },
            {
                id: "kommunikation-telefon-006",
                wortart: "Nomen",
                german: "Anrufbeantworter",
                artikel: "der",
                plural: "Anrufbeantworter",
                english: "answering machine",
                example_de: [{ "text": "Sind", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "Nachrichten", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "auf dem Anrufbeantworter", "kasus": "dativ" }, { "text": "?", "kasus": "none" }],
                example_en: "Are there messages on the answering machine?",
                cloze_parts: ["Sind Nachrichten auf dem ", "?"],
                cloze_answers: ["Anrufbeantworter"]
            },
            {
                id: "kommunikation-telefon-007",
                wortart: "Nomen",
                german: "Telefonnummer",
                artikel: "die",
                plural: "Telefonnummern",
                english: "phone number",
                example_de: [{ "text": "Bitte", "kasus": "none" }, { "text": ", ", "kasus": "none" }, { "text": "sag", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "mir", "kasus": "dativ" }, { "text": " ", "kasus": "none" }, { "text": "deine Telefonnummer", "kasus": "akkusativ" }, { "text": ".", "kasus": "none" }],
                example_en: "Please tell me your phone number.",
                cloze_parts: ["Bitte, sag mir deine ", "."],
                cloze_answers: ["Telefonnummer"]
            }
        ],

        // --- NEUE KATEGORIE 3: Internet ---
        "Internet": [
            {
                id: "kommunikation-internet-001",
                wortart: "Nomen",
                german: "Internet",
                artikel: "das",
                plural: null,
                english: "internet",
                example_de: [{ "text": "Wir", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "suchen", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "die Informationen", "kasus": "akkusativ" }, { "text": " ", "kasus": "none" }, { "text": "im Internet", "kasus": "dativ" }, { "text": ".", "kasus": "none" }],
                example_en: "We are looking for the information on the internet.",
                cloze_parts: ["Wir suchen die Informationen im ", "."],
                cloze_answers: ["Internet"]
            },
            {
                id: "kommunikation-internet-002",
                wortart: "Verb",
                german: "googeln",
                english: "to google",
                trennbar: false,
                hilfsverb_perfekt: "haben",
                partizip_ii: "gegoogelt",
                konjugation_praesens: { ich: "google", du: "googlest", er_sie_es: "googelt", wir: "googeln", ihr: "googelt", sie_Sie: "googeln" },
                imperativ: { du: "Google!", ihr: "Googelt!" },
                example_de: [{ "text": "Ich", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "google", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "den Namen", "kasus": "akkusativ" }, { "text": " ", "kasus": "none" }, { "text": "der Schauspielerin", "kasus": "genitiv" }, { "text": ".", "kasus": "none" }],
                example_en: "I am googling the actress's name.",
                cloze_parts: ["Ich ", " den Namen der Schauspielerin."],
                cloze_answers: ["google"]
            },
            {
                id: "kommunikation-internet-003",
                wortart: "Nomen",
                german: "Homepage",
                artikel: "die",
                plural: "Homepages",
                english: "homepage",
                example_de: [{ "text": "Die Homepage", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "der Schule", "kasus": "genitiv" }, { "text": " ", "kasus": "none" }, { "text": "ist", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "sehr interessant", "kasus": "none" }, { "text": ".", "kasus": "none" }],
                example_en: "The school's homepage is very interesting.",
                cloze_parts: ["Die ", " der Schule ist sehr interessant."],
                cloze_answers: ["Homepage"]
            },
            {
                id: "kommunikation-internet-004",
                wortart: "Nomen",
                german: "Link",
                artikel: "der",
                plural: "Links",
                english: "link",
                example_de: [{ "text": "Kannst", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "du", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "mir", "kasus": "dativ" }, { "text": " ", "kasus": "none" }, { "text": "den Link", "kasus": "akkusativ" }, { "text": " ", "kasus": "none" }, { "text": "schicken", "kasus": "verb" }, { "text": "?", "kasus": "none" }],
                example_en: "Can you send me the link?",
                cloze_parts: ["Kannst du mir den ", " schicken?"],
                cloze_answers: ["Link"]
            },
            {
                id: "kommunikation-internet-005",
                wortart: "Adjektiv",
                german: "online",
                english: "online",
                example_de: [{ "text": "Meine Freundin", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "ist", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "gerade", "kasus": "none" }, { "text": " ", "kasus": "none" }, { "text": "online", "kasus": "none" }, { "text": ".", "kasus": "none" }],
                example_en: "My friend is online right now.",
                cloze_parts: ["Meine Freundin ist gerade ", "."],
                cloze_answers: ["online"]
            },
            {
                id: "kommunikation-internet-006",
                wortart: "Verb",
                german: "surfen",
                english: "to surf (the internet)",
                trennbar: false,
                hilfsverb_perfekt: "haben",
                partizip_ii: "gesurft",
                konjugation_praesens: { ich: "surfe", du: "surfst", er_sie_es: "surft", wir: "surfen", ihr: "surft", sie_Sie: "surfen" },
                imperativ: { du: "Surf!", ihr: "Surft!" },
                example_de: [{ "text": "Am Abend", "kasus": "dativ" }, { "text": " ", "kasus": "none" }, { "text": "surfe", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "ich", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "gern", "kasus": "none" }, { "text": " ", "kasus": "none" }, { "text": "im Internet", "kasus": "dativ" }, { "text": ".", "kasus": "none" }],
                example_en: "In the evening I like to surf the internet.",
                cloze_parts: ["Am Abend ", " ich gern im Internet."],
                cloze_answers: ["surfe"]
            },
            {
                id: "kommunikation-internet-007",
                wortart: "Nomen",
                german: "Website",
                artikel: "die",
                plural: "Websites",
                english: "website",
                example_de: [{ "text": "Die Website", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "ist", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "sehr schön", "kasus": "none" }, { "text": ".", "kasus": "none" }],
                example_en: "The website is very nice.",
                cloze_parts: ["Die ", " ist sehr schön."],
                cloze_answers: ["Website"]
            },
            {
                id: "kommunikation-internet-008",
                wortart: "Verb",
                german: "chatten",
                english: "to chat",
                trennbar: false,
                hilfsverb_perfekt: "haben",
                partizip_ii: "gechattet",
                konjugation_praesens: { ich: "chatte", du: "chattest", er_sie_es: "chattet", wir: "chatten", ihr: "chattet", sie_Sie: "chatten" },
                imperativ: { du: "Chatt!", ihr: "Chattet!" },
                example_de: [{ "text": "Ich", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "chatte", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "gern", "kasus": "none" }, { "text": " ", "kasus": "none" }, { "text": "mit Freunden", "kasus": "dativ" }, { "text": ".", "kasus": "none" }],
                example_en: "I like to chat with friends.",
                cloze_parts: ["Ich ", " gern mit Freunden."],
                cloze_answers: ["chatte"]
            },
            {
                id: "kommunikation-internet-009",
                wortart: "Nomen",
                german: "Chat",
                artikel: "der",
                plural: "Chats",
                english: "chat",
                example_de: [{ "text": "Der Chat", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "war", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "interessant", "kasus": "none" }, { "text": ".", "kasus": "none" }],
                example_en: "The chat was interesting.",
                cloze_parts: ["Der ", " war interessant."],
                cloze_answers: ["Chat"]
            }
        ],

        // --- NEUE KATEGORIE 4: Verben der Kommunikation ---
        "Verben der Kommunikation": [
            {
                id: "kommunikation-verben-001",
                wortart: "Verb",
                german: "sprechen",
                english: "to speak",
                trennbar: false,
                hilfsverb_perfekt: "haben",
                partizip_ii: "gesprochen",
                konjugation_praesens: { ich: "spreche", du: "sprichst", er_sie_es: "spricht", wir: "sprechen", ihr: "sprecht", sie_Sie: "sprechen" },
                imperativ: { du: "Sprich!", ihr: "Sprecht!" },
                example_de: [{ "text": "Sie", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "spricht", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "mit dem Lehrer", "kasus": "dativ" }, { "text": ".", "kasus": "none" }],
                example_en: "She is speaking with the teacher.",
                cloze_parts: ["Sie ", " mit dem Lehrer."],
                cloze_answers: ["spricht"]
            },
            {
                id: "kommunikation-verben-002",
                wortart: "Verb",
                german: "sagen",
                english: "to say",
                trennbar: false,
                hilfsverb_perfekt: "haben",
                partizip_ii: "gesagt",
                konjugation_praesens: { ich: "sage", du: "sagst", er_sie_es: "sagt", wir: "sagen", ihr: "sagt", sie_Sie: "sagen" },
                imperativ: { du: "Sag!", ihr: "Sagt!" },
                example_de: [{ "text": "Eva", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "sagt", "kasus": "verb" }, { "text": ", ", "kasus": "none" }, { "text": "sie", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "kommt", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "heute", "kasus": "none" }, { "text": " ", "kasus": "none" }, { "text": "nicht", "kasus": "none" }, { "text": ".", "kasus": "none" }],
                example_en: "Eva says she is not coming today.",
                cloze_parts: ["Eva ", ", sie kommt heute nicht."],
                cloze_answers: ["sagt"]
            },
            {
                id: "kommunikation-verben-003",
                wortart: "Verb",
                german: "erzählen",
                english: "to tell / to narrate",
                trennbar: false,
                hilfsverb_perfekt: "haben",
                partizip_ii: "erzählt",
                konjugation_praesens: { ich: "erzähle", du: "erzählst", er_sie_es: "erzählt", wir: "erzählen", ihr: "erzählt", sie_Sie: "erzählen" },
                imperativ: { du: "Erzähl!", ihr: "Erzählt!" },
                example_de: [{ "text": "Kannst", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "du", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "die Geschichte", "kasus": "akkusativ" }, { "text": " ", "kasus": "none" }, { "text": "erzählen", "kasus": "verb" }, { "text": "?", "kasus": "none" }],
                example_en: "Can you tell the story?",
                cloze_parts: ["Kannst du die Geschichte ", "?"],
                cloze_answers: ["erzählen"]
            },
            {
                id: "kommunikation-verben-004",
                wortart: "Verb",
                german: "hören",
                english: "to hear / to listen",
                trennbar: false,
                hilfsverb_perfekt: "haben",
                partizip_ii: "gehört",
                konjugation_praesens: { ich: "höre", du: "hörst", er_sie_es: "hört", wir: "hören", ihr: "hört", sie_Sie: "hören" },
                imperativ: { du: "Hör!", ihr: "Hört!" },
                example_de: [{ "text": "Hörst", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "du", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "gern", "kasus": "none" }, { "text": " ", "kasus": "none" }, { "text": "Musik", "kasus": "akkusativ" }, { "text": "?", "kasus": "none" }],
                example_en: "Do you like to listen to music?",
                cloze_parts: ["", " du gern Musik?"],
                cloze_answers: ["Hörst"]
            },
            {
                id: "kommunikation-verben-005",
                wortart: "Verb",
                german: "zuhören",
                english: "to listen (to)",
                trennbar: true,
                hilfsverb_perfekt: "haben",
                partizip_ii: "zugehört",
                konjugation_praesens: { ich: "höre zu", du: "hörst zu", er_sie_es: "hört zu", wir: "hören zu", ihr: "hört zu", sie_Sie: "hören zu" },
                imperativ: { du: "Hör zu!", ihr: "Hört zu!" },
                example_de: [{ "text": "Hör", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "bitte", "kasus": "none" }, { "text": " ", "kasus": "none" }, { "text": "zu", "kasus": "verb" }, { "text": "!", "kasus": "none" }],
                example_en: "Please listen!",
                cloze_parts: ["", " bitte ", "!"],
                cloze_answers: ["Hör", "zu"]
            },
            {
                id: "kommunikation-verben-006",
                wortart: "Verb",
                german: "senden",
                english: "to send",
                trennbar: false,
                hilfsverb_perfekt: "haben",
                partizip_ii: "gesendet",
                konjugation_praesens: { ich: "sende", du: "sendest", er_sie_es: "sendet", wir: "senden", ihr: "sendet", sie_Sie: "senden" },
                imperativ: { du: "Sende!", ihr: "Sendet!" },
                example_de: [{ "text": "Ich", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "sende", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "dir", "kasus": "dativ" }, { "text": " ", "kasus": "none" }, { "text": "eine Nachricht", "kasus": "akkusativ" }, { "text": ".", "kasus": "none" }],
                example_en: "I am sending you a message.",
                cloze_parts: ["Ich ", " dir eine Nachricht."],
                cloze_answers: ["sende"]
            },
            {
                id: "kommunikation-verben-007",
                wortart: "Verb",
                german: "schicken",
                english: "to send",
                trennbar: false,
                hilfsverb_perfekt: "haben",
                partizip_ii: "geschickt",
                konjugation_praesens: { ich: "schicke", du: "schickst", er_sie_es: "schickt", wir: "schicken", ihr: "schickt", sie_Sie: "schicken" },
                imperativ: { du: "Schick!", ihr: "Schickt!" },
                example_de: [{ "text": "Wir", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "können", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "unseren Freunden", "kasus": "dativ" }, { "text": " ", "kasus": "none" }, { "text": "eine Karte", "kasus": "akkusativ" }, { "text": " ", "kasus": "none" }, { "text": "schicken", "kasus": "verb" }, { "text": ".", "kasus": "none" }],
                example_en: "We can send our friends a card.",
                cloze_parts: ["Wir können unseren Freunden eine Karte ", "."],
                cloze_answers: ["schicken"]
            },
            {
                id: "kommunikation-verben-008",
                wortart: "Verb",
                german: "bekommen",
                english: "to receive / to get",
                trennbar: false,
                hilfsverb_perfekt: "haben",
                partizip_ii: "bekommen",
                konjugation_praesens: { ich: "bekomme", du: "bekommst", er_sie_es: "bekommt", wir: "bekommen", ihr: "bekommt", sie_Sie: "bekommen" },
                imperativ: { du: "Bekomm!", ihr: "Bekommt!" },
                example_de: [{ "text": "Was", "kasus": "akkusativ" }, { "text": " ", "kasus": "none" }, { "text": "bekommst", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "du", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "zum Geburtstag", "kasus": "dativ" }, { "text": "?", "kasus": "none" }],
                example_en: "What are you getting for your birthday?",
                cloze_parts: ["Was ", " du zum Geburtstag?"],
                cloze_answers: ["bekommst"]
            },
            {
                id: "kommunikation-verben-009",
                wortart: "Verb",
                german: "empfangen",
                english: "to receive",
                trennbar: false,
                hilfsverb_perfekt: "haben",
                partizip_ii: "empfangen",
                konjugation_praesens: { ich: "empfange", du: "empfängst", er_sie_es: "empfängt", wir: "empfangen", ihr: "empfangt", sie_Sie: "empfangen" },
                imperativ: { du: "Empfang!", ihr: "Empfangt!" },
                example_de: [{ "text": "Ich", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "empfange", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "viele E-Mails", "kasus": "akkusativ" }, { "text": ".", "kasus": "none" }],
                example_en: "I receive many emails.",
                cloze_parts: ["Ich ", " viele E-Mails."],
                cloze_answers: ["empfange"]
            },
            {
                id: "kommunikation-verben-010",
                wortart: "Verb",
                german: "antworten",
                english: "to answer / to reply",
                trennbar: false,
                hilfsverb_perfekt: "haben",
                partizip_ii: "geantwortet",
                konjugation_praesens: { ich: "antworte", du: "antwortest", er_sie_es: "antwortet", wir: "antworten", ihr: "antwortet", sie_Sie: "antworten" },
                imperativ: { du: "Antworte!", ihr: "Antwortet!" },
                example_de: [{ "text": "Warum", "kasus": "none" }, { "text": " ", "kasus": "none" }, { "text": "antwortest", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "du", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "nicht", "kasus": "none" }, { "text": "?", "kasus": "none" }],
                example_en: "Why don't you answer?",
                cloze_parts: ["Warum ", " du nicht?"],
                cloze_answers: ["antwortest"]
            }
        ]
    }
};