// vokabular_kommunikationsmittel.ts

import type { 
    VocabularyStructure, 
    Word, 
    Noun,
    Verb,
    Adjective,
    WordId,
    CaseElement 
} from './src/core/types/vocabulary';
import { createWordId, createVocabulary } from './src/core/types/vocabulary';

export const vokabularKommunikationsmittel: VocabularyStructure = createVocabulary({
    "Kommunikationsmittel": {

        // --- SUB-TOPIC: Schriftliche Kommunikation ---
        "Schriftliche Kommunikation": [
            {
                id: createWordId("kommunikation-schriftlich-001"),
                wordType: 'noun',
                german: "E-Mail",
                article: "die",
                plural: "E-Mails",
                english: "email",
                exampleGerman: [
                    { text: "Danke", case: "none" },
                    { text: " ", case: "none" },
                    { text: "für", case: "none" },
                    { text: " ", case: "none" },
                    { text: "deine", case: "none" },
                    { text: " ", case: "none" },
                    { text: "E-Mail", case: "akkusativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "Thank you for your email.",
                clozeParts: ["Danke für deine ", "."],
                clozeAnswers: ["E-Mail"]
            } as Noun,
            {
                id: createWordId("kommunikation-schriftlich-002"),
                wordType: 'verb',
                german: "mailen",
                english: "to email",
                separable: false,
                auxiliaryVerb: "haben",
                pastParticiple: "gemailt",
                presentConjugation: { ich: "maile", du: "mailst", er: "mailt", wir: "mailen", ihr: "mailt", sie: "mailen" },
                imperative: { du: "Maile!", ihr: "Mailt!" },
                exampleGerman: [
                    { text: "Ich", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "maile", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "dir", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "die", case: "none" },
                    { text: " ", case: "none" },
                    { text: "Fotos", case: "akkusativ" },
                    { text: " ", case: "none" },
                    { text: "morgen", case: "none" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "I will email you the photos tomorrow.",
                clozeParts: ["Ich ", " dir die Fotos morgen."],
                clozeAnswers: ["maile"]
            } as Verb,
            {
                id: createWordId("kommunikation-schriftlich-003"),
                wordType: 'noun',
                german: "Mailbox",
                article: "die",
                plural: "Mailboxen",
                english: "mailbox",
                exampleGerman: [
                    { text: "In", case: "none" },
                    { text: " ", case: "none" },
                    { text: "meiner", case: "none" },
                    { text: " ", case: "none" },
                    { text: "Mailbox", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "sind", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "drei", case: "none" },
                    { text: " ", case: "none" },
                    { text: "neue", case: "none" },
                    { text: " ", case: "none" },
                    { text: "Nachrichten", case: "nominativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "There are three new messages in my mailbox.",
                clozeParts: ["In meiner ", " sind drei neue Nachrichten."],
                clozeAnswers: ["Mailbox"]
            } as Noun,
            {
                id: createWordId("kommunikation-schriftlich-004"),
                wordType: 'noun',
                german: "Brief",
                article: "der",
                plural: "Briefe",
                english: "letter",
                exampleGerman: [
                    { text: "Sie", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "bekommt", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "immer", case: "none" },
                    { text: " ", case: "none" },
                    { text: "viele", case: "none" },
                    { text: " ", case: "none" },
                    { text: "Briefe", case: "akkusativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "She always receives many letters.",
                clozeParts: ["Sie bekommt immer viele ", "."],
                clozeAnswers: ["Briefe"]
            } as Noun,
            {
                id: createWordId("kommunikation-schriftlich-005"),
                wordType: 'noun',
                german: "Postkarte",
                article: "die",
                plural: "Postkarten",
                english: "postcard",
                exampleGerman: [
                    { text: "Wir", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "schreiben", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "ihm", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "eine", case: "none" },
                    { text: " ", case: "none" },
                    { text: "Postkarte", case: "akkusativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "We are writing him a postcard.",
                clozeParts: ["Wir schreiben ihm eine ", "."],
                clozeAnswers: ["Postkarte"]
            } as Noun,
            {
                id: createWordId("kommunikation-schriftlich-006"),
                wordType: 'noun',
                german: "Nachricht",
                article: "die",
                plural: "Nachrichten",
                english: "message",
                exampleGerman: [
                    { text: "Du", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "hörst", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "die", case: "none" },
                    { text: " ", case: "none" },
                    { text: "Nachricht", case: "akkusativ" },
                    { text: " ", case: "none" },
                    { text: "noch", case: "none" },
                    { text: " ", case: "none" },
                    { text: "einmal", case: "none" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "You hear the message once more.",
                clozeParts: ["Du hörst die ", " noch einmal."],
                clozeAnswers: ["Nachricht"]
            } as Noun
        ],

        // --- SUB-TOPIC: Telefon ---
        "Telefon": [
            {
                id: createWordId("kommunikation-telefon-001"),
                wordType: 'noun',
                german: "Handy",
                article: "das",
                plural: "Handys",
                english: "mobile phone",
                exampleGerman: [
                    { text: "Du", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "kannst", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "mit", case: "none" },
                    { text: " ", case: "none" },
                    { text: "dem", case: "none" },
                    { text: " ", case: "none" },
                    { text: "Handy", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "telefonieren", case: "verb" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "You can make phone calls with the mobile phone.",
                clozeParts: ["Du kannst mit dem ", " telefonieren."],
                clozeAnswers: ["Handy"]
            } as Noun,
            {
                id: createWordId("kommunikation-telefon-002"),
                wordType: 'noun',
                german: "Telefon",
                article: "das",
                plural: "Telefone",
                english: "telephone",
                exampleGerman: [
                    { text: "Das", case: "none" },
                    { text: " ", case: "none" },
                    { text: "Telefon", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "klingelt", case: "verb" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "The telephone is ringing.",
                clozeParts: ["Das ", " klingelt."],
                clozeAnswers: ["Telefon"]
            } as Noun,
            {
                id: createWordId("kommunikation-telefon-003"),
                wordType: 'verb',
                german: "telefonieren",
                english: "to make a phone call",
                separable: false,
                auxiliaryVerb: "haben",
                pastParticiple: "telefoniert",
                presentConjugation: { ich: "telefoniere", du: "telefonierst", er: "telefoniert", wir: "telefonieren", ihr: "telefoniert", sie: "telefonieren" },
                imperative: { du: "Telefonier!", ihr: "Telefoniert!" },
                exampleGerman: [
                    { text: "Ich", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "telefoniere", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "oft", case: "none" },
                    { text: " ", case: "none" },
                    { text: "mit", case: "none" },
                    { text: " ", case: "none" },
                    { text: "meiner", case: "none" },
                    { text: " ", case: "none" },
                    { text: "Freundin", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "in", case: "none" },
                    { text: " ", case: "none" },
                    { text: "Frankfurt", case: "dativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "I often make phone calls with my friend in Frankfurt.",
                clozeParts: ["Ich ", " oft mit meiner Freundin in Frankfurt."],
                clozeAnswers: ["telefoniere"]
            } as Verb,
            {
                id: createWordId("kommunikation-telefon-004"),
                wordType: 'verb',
                german: "anrufen",
                english: "to call",
                separable: true,
                auxiliaryVerb: "haben",
                pastParticiple: "angerufen",
                presentConjugation: { ich: "rufe an", du: "rufst an", er: "ruft an", wir: "rufen an", ihr: "ruft an", sie: "rufen an" },
                imperative: { du: "Ruf an!", ihr: "Ruft an!" },
                exampleGerman: [
                    { text: "Ich", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "rufe", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "dich", case: "akkusativ" },
                    { text: " ", case: "none" },
                    { text: "morgen", case: "none" },
                    { text: " ", case: "none" },
                    { text: "an", case: "verb" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "I will call you tomorrow.",
                clozeParts: ["Ich ", " dich morgen ", "."],
                clozeAnswers: ["rufe", "an"]
            } as Verb,
            {
                id: createWordId("kommunikation-telefon-005"),
                wordType: 'noun',
                german: "Anruf",
                article: "der",
                plural: "Anrufe",
                english: "call",
                exampleGerman: [
                    { text: "Ich", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "warte", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "dann", case: "none" },
                    { text: " ", case: "none" },
                    { text: "auf", case: "none" },
                    { text: " ", case: "none" },
                    { text: "deinen", case: "none" },
                    { text: " ", case: "none" },
                    { text: "Anruf", case: "akkusativ" },
                    { text: " ", case: "none" },
                    { text: "-", case: "none" },
                    { text: " ", case: "none" },
                    { text: "okay", case: "none" },
                    { text: "?", case: "none" }
                ],
                exampleEnglish: "I'll wait for your call then - okay?",
                clozeParts: ["Ich warte dann auf deinen ", " - okay?"],
                clozeAnswers: ["Anruf"]
            } as Noun,
            {
                id: createWordId("kommunikation-telefon-006"),
                wordType: 'noun',
                german: "Anrufbeantworter",
                article: "der",
                plural: "Anrufbeantworter",
                english: "answering machine",
                exampleGerman: [
                    { text: "Sind", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "Nachrichten", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "auf", case: "none" },
                    { text: " ", case: "none" },
                    { text: "dem", case: "none" },
                    { text: " ", case: "none" },
                    { text: "Anrufbeantworter", case: "dativ" },
                    { text: "?", case: "none" }
                ],
                exampleEnglish: "Are there messages on the answering machine?",
                clozeParts: ["Sind Nachrichten auf dem ", "?"],
                clozeAnswers: ["Anrufbeantworter"]
            } as Noun,
            {
                id: createWordId("kommunikation-telefon-007"),
                wordType: 'noun',
                german: "Telefonnummer",
                article: "die",
                plural: "Telefonnummern",
                english: "phone number",
                exampleGerman: [
                    { text: "Bitte", case: "none" },
                    { text: ",", case: "none" },
                    { text: " ", case: "none" },
                    { text: "sag", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "mir", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "deine", case: "none" },
                    { text: " ", case: "none" },
                    { text: "Telefonnummer", case: "akkusativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "Please tell me your phone number.",
                clozeParts: ["Bitte, sag mir deine ", "."],
                clozeAnswers: ["Telefonnummer"]
            } as Noun
        ],

        // --- SUB-TOPIC: Internet ---
        "Internet": [
            {
                id: createWordId("kommunikation-internet-001"),
                wordType: 'noun',
                german: "Internet",
                article: "das",
                plural: null, // oft ohne Plural
                english: "internet",
                exampleGerman: [
                    { text: "Wir", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "suchen", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "die", case: "none" },
                    { text: " ", case: "none" },
                    { text: "Informationen", case: "akkusativ" },
                    { text: " ", case: "none" },
                    { text: "im", case: "none" },
                    { text: " ", case: "none" },
                    { text: "Internet", case: "dativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "We are looking for the information on the internet.",
                clozeParts: ["Wir suchen die Informationen im ", "."],
                clozeAnswers: ["Internet"]
            } as Noun,
            {
                id: createWordId("kommunikation-internet-002"),
                wordType: 'verb',
                german: "googeln",
                english: "to google",
                separable: false,
                auxiliaryVerb: "haben",
                pastParticiple: "gegoogelt",
                presentConjugation: { ich: "google", du: "googlest", er: "googelt", wir: "googeln", ihr: "googelt", sie: "googeln" },
                imperative: { du: "Google!", ihr: "Googelt!" },
                exampleGerman: [
                    { text: "Ich", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "google", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "den", case: "none" },
                    { text: " ", case: "none" },
                    { text: "Namen", case: "akkusativ" },
                    { text: " ", case: "none" },
                    { text: "der", case: "none" },
                    { text: " ", case: "none" },
                    { text: "Schauspielerin", case: "genitiv" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "I am googling the actress's name.",
                clozeParts: ["Ich ", " den Namen der Schauspielerin."],
                clozeAnswers: ["google"]
            } as Verb,
            {
                id: createWordId("kommunikation-internet-003"),
                wordType: 'noun',
                german: "Homepage",
                article: "die",
                plural: "Homepages",
                english: "homepage",
                exampleGerman: [
                    { text: "Die", case: "none" },
                    { text: " ", case: "none" },
                    { text: "Homepage", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "der", case: "none" },
                    { text: " ", case: "none" },
                    { text: "Schule", case: "genitiv" },
                    { text: " ", case: "none" },
                    { text: "ist", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "sehr", case: "none" },
                    { text: " ", case: "none" },
                    { text: "interessant", case: "none" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "The school's homepage is very interesting.",
                clozeParts: ["Die ", " der Schule ist sehr interessant."],
                clozeAnswers: ["Homepage"]
            } as Noun,
            {
                id: createWordId("kommunikation-internet-004"),
                wordType: 'noun',
                german: "Link",
                article: "der",
                plural: "Links",
                english: "link",
                exampleGerman: [
                    { text: "Kannst", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "du", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "mir", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "den", case: "none" },
                    { text: " ", case: "none" },
                    { text: "Link", case: "akkusativ" },
                    { text: " ", case: "none" },
                    { text: "schicken", case: "verb" },
                    { text: "?", case: "none" }
                ],
                exampleEnglish: "Can you send me the link?",
                clozeParts: ["Kannst du mir den ", " schicken?"],
                clozeAnswers: ["Link"]
            } as Noun,
            {
                id: createWordId("kommunikation-internet-005"),
                wordType: 'adjective',
                german: "online",
                english: "online",
                exampleGerman: [
                    { text: "Meine", case: "none" },
                    { text: " ", case: "none" },
                    { text: "Freundin", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "ist", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "gerade", case: "none" },
                    { text: " ", case: "none" },
                    { text: "online", case: "none" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "My friend is online right now.",
                clozeParts: ["Meine Freundin ist gerade ", "."],
                clozeAnswers: ["online"]
            } as Adjective,
            {
                id: createWordId("kommunikation-internet-006"),
                wordType: 'verb',
                german: "surfen",
                english: "to surf (the internet)",
                separable: false,
                auxiliaryVerb: "haben",
                pastParticiple: "gesurft",
                presentConjugation: { ich: "surfe", du: "surfst", er: "surft", wir: "surfen", ihr: "surft", sie: "surfen" },
                imperative: { du: "Surf!", ihr: "Surft!" },
                exampleGerman: [
                    { text: "Am", case: "none" },
                    { text: " ", case: "none" },
                    { text: "Abend", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "surfe", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "ich", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "gern", case: "none" },
                    { text: " ", case: "none" },
                    { text: "im", case: "none" },
                    { text: " ", case: "none" },
                    { text: "Internet", case: "dativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "In the evening I like to surf the internet.",
                clozeParts: ["Am Abend ", " ich gern im Internet."],
                clozeAnswers: ["surfe"]
            } as Verb,
            {
                id: createWordId("kommunikation-internet-007"),
                wordType: 'noun',
                german: "Website",
                article: "die",
                plural: "Websites",
                english: "website",
                exampleGerman: [
                    { text: "Die", case: "none" },
                    { text: " ", case: "none" },
                    { text: "Website", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "ist", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "sehr", case: "none" },
                    { text: " ", case: "none" },
                    { text: "schön", case: "none" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "The website is very nice.",
                clozeParts: ["Die ", " ist sehr schön."],
                clozeAnswers: ["Website"]
            } as Noun,
            {
                id: createWordId("kommunikation-internet-008"),
                wordType: 'verb',
                german: "chatten",
                english: "to chat",
                separable: false,
                auxiliaryVerb: "haben",
                pastParticiple: "gechattet",
                presentConjugation: { ich: "chatte", du: "chattest", er: "chattet", wir: "chatten", ihr: "chattet", sie: "chatten" },
                imperative: { du: "Chatt!", ihr: "Chattet!" },
                exampleGerman: [
                    { text: "Ich", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "chatte", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "gern", case: "none" },
                    { text: " ", case: "none" },
                    { text: "mit", case: "none" },
                    { text: " ", case: "none" },
                    { text: "Freunden", case: "dativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "I like to chat with friends.",
                clozeParts: ["Ich ", " gern mit Freunden."],
                clozeAnswers: ["chatte"]
            } as Verb,
            {
                id: createWordId("kommunikation-internet-009"),
                wordType: 'noun',
                german: "Chat",
                article: "der",
                plural: "Chats",
                english: "chat",
                exampleGerman: [
                    { text: "Der", case: "none" },
                    { text: " ", case: "none" },
                    { text: "Chat", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "war", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "interessant", case: "none" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "The chat was interesting.",
                clozeParts: ["Der ", " war interessant."],
                clozeAnswers: ["Chat"]
            } as Noun
        ],

        // --- SUB-TOPIC: Verben der Kommunikation ---
        "Verben der Kommunikation": [
            {
                id: createWordId("kommunikation-verben-001"),
                wordType: 'verb',
                german: "sprechen",
                english: "to speak",
                separable: false,
                auxiliaryVerb: "haben",
                pastParticiple: "gesprochen",
                presentConjugation: { ich: "spreche", du: "sprichst", er: "spricht", wir: "sprechen", ihr: "sprecht", sie: "sprechen" },
                imperative: { du: "Sprich!", ihr: "Sprecht!" },
                exampleGerman: [
                    { text: "Sie", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "spricht", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "mit", case: "none" },
                    { text: " ", case: "none" },
                    { text: "dem", case: "none" },
                    { text: " ", case: "none" },
                    { text: "Lehrer", case: "dativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "She is speaking with the teacher.",
                clozeParts: ["Sie ", " mit dem Lehrer."],
                clozeAnswers: ["spricht"]
            } as Verb,
            {
                id: createWordId("kommunikation-verben-002"),
                wordType: 'verb',
                german: "sagen",
                english: "to say",
                separable: false,
                auxiliaryVerb: "haben",
                pastParticiple: "gesagt",
                presentConjugation: { ich: "sage", du: "sagst", er: "sagt", wir: "sagen", ihr: "sagt", sie: "sagen" },
                imperative: { du: "Sag!", ihr: "Sagt!" },
                exampleGerman: [
                    { text: "Eva", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "sagt", case: "verb" },
                    { text: ",", case: "none" },
                    { text: " ", case: "none" },
                    { text: "sie", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "kommt", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "heute", case: "none" },
                    { text: " ", case: "none" },
                    { text: "nicht", case: "none" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "Eva says she is not coming today.",
                clozeParts: ["Eva ", ", sie kommt heute nicht."],
                clozeAnswers: ["sagt"]
            } as Verb,
            {
                id: createWordId("kommunikation-verben-003"),
                wordType: 'verb',
                german: "erzählen",
                english: "to tell / to narrate",
                separable: false,
                auxiliaryVerb: "haben",
                pastParticiple: "erzählt",
                presentConjugation: { ich: "erzähle", du: "erzählst", er: "erzählt", wir: "erzählen", ihr: "erzählt", sie: "erzählen" },
                imperative: { du: "Erzähl!", ihr: "Erzählt!" },
                exampleGerman: [
                    { text: "Kannst", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "du", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "die", case: "none" },
                    { text: " ", case: "none" },
                    { text: "Geschichte", case: "akkusativ" },
                    { text: " ", case: "none" },
                    { text: "erzählen", case: "verb" },
                    { text: "?", case: "none" }
                ],
                exampleEnglish: "Can you tell the story?",
                clozeParts: ["Kannst du die Geschichte ", "?"],
                clozeAnswers: ["erzählen"]
            } as Verb,
            {
                id: createWordId("kommunikation-verben-004"),
                wordType: 'verb',
                german: "hören",
                english: "to hear / to listen",
                separable: false,
                auxiliaryVerb: "haben",
                pastParticiple: "gehört",
                presentConjugation: { ich: "höre", du: "hörst", er: "hört", wir: "hören", ihr: "hört", sie: "hören" },
                imperative: { du: "Hör!", ihr: "Hört!" },
                exampleGerman: [
                    { text: "Hörst", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "du", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "gern", case: "none" },
                    { text: " ", case: "none" },
                    { text: "Musik", case: "akkusativ" },
                    { text: "?", case: "none" }
                ],
                exampleEnglish: "Do you like to listen to music?",
                clozeParts: ["", " du gern Musik?"],
                clozeAnswers: ["Hörst"]
            } as Verb,
            {
                id: createWordId("kommunikation-verben-005"),
                wordType: 'verb',
                german: "zuhören",
                english: "to listen (to)",
                separable: true,
                auxiliaryVerb: "haben",
                pastParticiple: "zugehört",
                presentConjugation: { ich: "höre zu", du: "hörst zu", er: "hört zu", wir: "hören zu", ihr: "hört zu", sie: "hören zu" },
                imperative: { du: "Hör zu!", ihr: "Hört zu!" },
                exampleGerman: [
                    { text: "Hör", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "bitte", case: "none" },
                    { text: " ", case: "none" },
                    { text: "zu", case: "verb" },
                    { text: "!", case: "none" }
                ],
                exampleEnglish: "Please listen!",
                clozeParts: ["", " bitte ", "!"],
                clozeAnswers: ["Hör", "zu"]
            } as Verb,
            {
                id: createWordId("kommunikation-verben-006"),
                wordType: 'verb',
                german: "senden",
                english: "to send",
                separable: false,
                auxiliaryVerb: "haben",
                pastParticiple: "gesendet",
                presentConjugation: { ich: "sende", du: "sendest", er: "sendet", wir: "senden", ihr: "sendet", sie: "senden" },
                imperative: { du: "Sende!", ihr: "Sendet!" },
                exampleGerman: [
                    { text: "Ich", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "sende", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "dir", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "eine", case: "none" },
                    { text: " ", case: "none" },
                    { text: "Nachricht", case: "akkusativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "I am sending you a message.",
                clozeParts: ["Ich ", " dir eine Nachricht."],
                clozeAnswers: ["sende"]
            } as Verb,
            {
                id: createWordId("kommunikation-verben-007"),
                wordType: 'verb',
                german: "schicken",
                english: "to send",
                separable: false,
                auxiliaryVerb: "haben",
                pastParticiple: "geschickt",
                presentConjugation: { ich: "schicke", du: "schickst", er: "schickt", wir: "schicken", ihr: "schickt", sie: "schicken" },
                imperative: { du: "Schick!", ihr: "Schickt!" },
                exampleGerman: [
                    { text: "Wir", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "können", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "unseren", case: "none" },
                    { text: " ", case: "none" },
                    { text: "Freunden", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "eine", case: "none" },
                    { text: " ", case: "none" },
                    { text: "Karte", case: "akkusativ" },
                    { text: " ", case: "none" },
                    { text: "schicken", case: "verb" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "We can send our friends a card.",
                clozeParts: ["Wir können unseren Freunden eine Karte ", "."],
                clozeAnswers: ["schicken"]
            } as Verb,
            {
                id: createWordId("kommunikation-verben-008"),
                wordType: 'verb',
                german: "bekommen",
                english: "to receive / to get",
                separable: false,
                auxiliaryVerb: "haben",
                pastParticiple: "bekommen",
                presentConjugation: { ich: "bekomme", du: "bekommst", er: "bekommt", wir: "bekommen", ihr: "bekommt", sie: "bekommen" },
                imperative: { du: "Bekomm!", ihr: "Bekommt!" },
                exampleGerman: [
                    { text: "Was", case: "akkusativ" },
                    { text: " ", case: "none" },
                    { text: "bekommst", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "du", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "zum", case: "none" },
                    { text: " ", case: "none" },
                    { text: "Geburtstag", case: "dativ" },
                    { text: "?", case: "none" }
                ],
                exampleEnglish: "What are you getting for your birthday?",
                clozeParts: ["Was ", " du zum Geburtstag?"],
                clozeAnswers: ["bekommst"]
            } as Verb,
            {
                id: createWordId("kommunikation-verben-009"),
                wordType: 'verb',
                german: "empfangen",
                english: "to receive",
                separable: false,
                auxiliaryVerb: "haben",
                pastParticiple: "empfangen",
                presentConjugation: { ich: "empfange", du: "empfängst", er: "empfängt", wir: "empfangen", ihr: "empfangt", sie: "empfangen" },
                imperative: { du: "Empfang!", ihr: "Empfangt!" },
                exampleGerman: [
                    { text: "Ich", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "empfange", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "viele", case: "none" },
                    { text: " ", case: "none" },
                    { text: "E-Mails", case: "akkusativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "I receive many emails.",
                clozeParts: ["Ich ", " viele E-Mails."],
                clozeAnswers: ["empfange"]
            } as Verb,
            {
                id: createWordId("kommunikation-verben-010"),
                wordType: 'verb',
                german: "antworten",
                english: "to answer / to reply",
                separable: false,
                auxiliaryVerb: "haben",
                pastParticiple: "geantwortet",
                presentConjugation: { ich: "antworte", du: "antwortest", er: "antwortet", wir: "antworten", ihr: "antwortet", sie: "antworten" },
                imperative: { du: "Antworte!", ihr: "Antwortet!" },
                exampleGerman: [
                    { text: "Warum", case: "none" },
                    { text: " ", case: "none" },
                    { text: "antwortest", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "du", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "nicht", case: "none" },
                    { text: "?", case: "none" }
                ],
                exampleEnglish: "Why don't you answer?",
                clozeParts: ["Warum ", " du nicht?"],
                clozeAnswers: ["antwortest"]
            } as Verb
        ]
    }
});