// vokabular_wohnen.ts

import type { VocabularyStructure, Word, Noun, Verb, Adjective, WordId, CaseElement } from './src/core/types/vocabulary';
import { createWordId, createVocabulary } from './src/core/types/vocabulary';

export const vokabularWohnen: VocabularyStructure = createVocabulary({
    "Wohnen": {
        // --- KATEGORIE 1: Räume und Gebäudeteile (12 Vokabeln) ---
        "Räume und Gebäudeteile": [
            {
                id: createWordId("wohnen-zimmer-001"),
                wordType: "noun",
                german: "Zimmer",
                article: "das",
                plural: "Zimmer",
                english: "room",
                exampleGerman: [
                    { text: "Räum", case: "none" },
                    { text: " ", case: "none" },
                    { text: "bitte", case: "none" },
                    { text: " ", case: "none" },
                    { text: "dein", case: "none" },
                    { text: " ", case: "none" },
                    { text: "Zimmer", case: "akkusativ" },
                    { text: " ", case: "none" },
                    { text: "auf", case: "none" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "Please tidy up your room.",
                clozeParts: ["Räum bitte dein ", " auf."],
                clozeAnswers: ["Zimmer"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-014"),
                wordType: "noun",
                german: "Fenster",
                article: "das",
                plural: "Fenster",
                english: "window",
                exampleGerman: [
                    { text: "Ich", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "möchte", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "einen", case: "akkusativ" },
                    { text: " ", case: "none" },
                    { text: "Platz", case: "akkusativ" },
                    { text: " ", case: "none" },
                    { text: "am", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "Fenster", case: "dativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "I would like a seat by the window.",
                clozeParts: ["Ich möchte einen Platz am ", "."],
                clozeAnswers: ["Fenster"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-015"),
                wordType: "noun",
                german: "Tür",
                article: "die",
                plural: "Türen",
                english: "door",
                exampleGerman: [
                    { text: "Die", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Tür", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "ist", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "zu", case: "none" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "The door is closed.",
                clozeParts: ["Die ", " ist zu."],
                clozeAnswers: ["Tür"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-016"),
                wordType: "noun",
                german: "Wand",
                article: "die",
                plural: "Wände",
                english: "wall",
                exampleGerman: [
                    { text: "An", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "der", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "Wand", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "hängt", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "ein", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Bild", case: "nominativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "A picture hangs on the wall.",
                clozeParts: ["An der ", " hängt ein Bild."],
                clozeAnswers: ["Wand"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-022"),
                wordType: "noun",
                german: "Boden",
                article: "der",
                plural: "Böden",
                english: "floor / ground",
                exampleGerman: [
                    { text: "Die", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Tasche", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "steht", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "auf", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "dem", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "Boden", case: "dativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "The bag is on the floor.",
                clozeParts: ["Die Tasche steht auf dem ", "."],
                clozeAnswers: ["Boden"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-026"),
                wordType: "noun",
                german: "Bad",
                article: "das",
                plural: "Bäder",
                english: "bathroom",
                exampleGerman: [
                    { text: "Wo", case: "none" },
                    { text: " ", case: "none" },
                    { text: "ist", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "das", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Bad", case: "nominativ" },
                    { text: "?", case: "none" }
                ],
                exampleEnglish: "Where is the bathroom?",
                clozeParts: ["Wo ist das ", "?"],
                clozeAnswers: ["Bad"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-027"),
                wordType: "noun",
                german: "Dusche",
                article: "die",
                plural: "Duschen",
                english: "shower",
                exampleGerman: [
                    { text: "Die", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Dusche", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "ist", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "kaputt", case: "none" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "The shower is broken.",
                clozeParts: ["Die ", " ist kaputt."],
                clozeAnswers: ["Dusche"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-028"),
                wordType: "noun",
                german: "Toilette/WC",
                article: "die",
                plural: "Toiletten/WCs",
                english: "toilet / WC",
                exampleGerman: [
                    { text: "Wo", case: "none" },
                    { text: " ", case: "none" },
                    { text: "ist", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "die", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Toilette", case: "nominativ" },
                    { text: "?", case: "none" }
                ],
                exampleEnglish: "Where is the toilet?",
                clozeParts: ["Wo ist die ", "?"],
                clozeAnswers: ["Toilette"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-029"),
                wordType: "noun",
                german: "Küche",
                article: "die",
                plural: "Küchen",
                english: "kitchen",
                exampleGerman: [
                    { text: "In", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "der", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "Küche", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "kocht", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "meine", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Mutter", case: "nominativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "My mother is cooking in the kitchen.",
                clozeParts: ["In der ", " kocht meine Mutter."],
                clozeAnswers: ["Küche"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-034"),
                wordType: "noun",
                german: "Fensterbank",
                article: "die",
                plural: "Fensterbänke",
                english: "windowsill",
                exampleGerman: [
                    { text: "Die", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Blumen", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "stehen", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "auf", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "der", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "Fensterbank", case: "dativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "The flowers are on the windowsill.",
                clozeParts: ["Die Blumen stehen auf der ", "."],
                clozeAnswers: ["Fensterbank"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-036"),
                wordType: "noun",
                german: "Flur",
                article: "der",
                plural: "Flure",
                english: "hallway / corridor",
                exampleGerman: [
                    { text: "Die", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Schuhe", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "stehen", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "im", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "Flur", case: "dativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "The shoes are in the hallway.",
                clozeParts: ["Die Schuhe stehen im ", "."],
                clozeAnswers: ["Flur"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-037"),
                wordType: "noun",
                german: "Balkon",
                article: "der",
                plural: "Balkone",
                english: "balcony",
                exampleGerman: [
                    { text: "Wir", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "haben", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "einen", case: "akkusativ" },
                    { text: " ", case: "none" },
                    { text: "Balkon", case: "akkusativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "We have a balcony.",
                clozeParts: ["Wir haben einen ", "."],
                clozeAnswers: ["Balkon"]
            } as Noun
        ],

        // --- KATEGORIE 2: Möbel und Einrichtung (18 Vokabeln) ---
        "Möbel und Einrichtung": [
            {
                id: createWordId("wohnen-zimmer-002"),
                wordType: "noun",
                german: "Bett",
                article: "das",
                plural: "Betten",
                english: "bed",
                exampleGerman: [
                    { text: "Wann", case: "none" },
                    { text: " ", case: "none" },
                    { text: "gehst", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "du", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "ins", case: "akkusativ" },
                    { text: " ", case: "none" },
                    { text: "Bett", case: "akkusativ" },
                    { text: "?", case: "none" }
                ],
                exampleEnglish: "When do you go to bed?",
                clozeParts: ["Wann gehst du ins ", "?"],
                clozeAnswers: ["Bett"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-003"),
                wordType: "noun",
                german: "Schrank",
                article: "der",
                plural: "Schränke",
                english: "closet / wardrobe",
                exampleGerman: [
                    { text: "Im", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "Schrank", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "sind", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "meine", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Kleider", case: "nominativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "My clothes are in the closet.",
                clozeParts: ["Im ", " sind meine Kleider."],
                clozeAnswers: ["Schrank"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-004"),
                wordType: "noun",
                german: "Regal",
                article: "das",
                plural: "Regale",
                english: "shelf / rack",
                exampleGerman: [
                    { text: "Die", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Bücher", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "stehen", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "im", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "Regal", case: "dativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "The books are on the shelf.",
                clozeParts: ["Die Bücher stehen im ", "."],
                clozeAnswers: ["Regal"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-005"),
                wordType: "noun",
                german: "Tisch",
                article: "der",
                plural: "Tische",
                english: "table",
                exampleGerman: [
                    { text: "Der", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Tisch", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "steht", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "im", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "Wohnzimmer", case: "dativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "The table is in the living room.",
                clozeParts: ["Der ", " steht im Wohnzimmer."],
                clozeAnswers: ["Tisch"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-006"),
                wordType: "noun",
                german: "Stuhl",
                article: "der",
                plural: "Stühle",
                english: "chair",
                exampleGerman: [
                    { text: "Auf", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "dem", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "Stuhl", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "liegt", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "meine", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Jacke", case: "nominativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "My jacket is on the chair.",
                clozeParts: ["Auf dem ", " liegt meine Jacke."],
                clozeAnswers: ["Stuhl"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-007"),
                wordType: "noun",
                german: "Sessel",
                article: "der",
                plural: "Sessel",
                english: "armchair",
                exampleGerman: [
                    { text: "Ich", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "sitze", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "gern", case: "none" },
                    { text: " ", case: "none" },
                    { text: "im", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "Sessel", case: "dativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "I like to sit in the armchair.",
                clozeParts: ["Ich sitze gern im ", "."],
                clozeAnswers: ["Sessel"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-008"),
                wordType: "noun",
                german: "Sofa",
                article: "das",
                plural: "Sofas",
                english: "sofa / couch",
                exampleGerman: [
                    { text: "Das", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Sofa", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "ist", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "bequem", case: "none" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "The sofa is comfortable.",
                clozeParts: ["Das ", " ist bequem."],
                clozeAnswers: ["Sofa"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-009"),
                wordType: "noun",
                german: "Decke",
                article: "die",
                plural: "Decken",
                english: "blanket / ceiling",
                exampleGerman: [
                    { text: "Die", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Decke", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "ist", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "warm", case: "none" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "The blanket is warm.",
                clozeParts: ["Die ", " ist warm."],
                clozeAnswers: ["Decke"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-010"),
                wordType: "noun",
                german: "Kissen",
                article: "das",
                plural: "Kissen",
                english: "pillow / cushion",
                exampleGerman: [
                    { text: "Ich", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "brauche", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "ein", case: "akkusativ" },
                    { text: " ", case: "none" },
                    { text: "Kissen", case: "akkusativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "I need a pillow.",
                clozeParts: ["Ich brauche ein ", "."],
                clozeAnswers: ["Kissen"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-011"),
                wordType: "noun",
                german: "Teppich",
                article: "der",
                plural: "Teppiche",
                english: "carpet / rug",
                exampleGerman: [
                    { text: "Der", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Teppich", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "ist", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "bunt", case: "none" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "The carpet is colorful.",
                clozeParts: ["Der ", " ist bunt."],
                clozeAnswers: ["Teppich"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-012"),
                wordType: "noun",
                german: "Lampe",
                article: "die",
                plural: "Lampen",
                english: "lamp",
                exampleGerman: [
                    { text: "Die", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Lampe", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "ist", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "kaputt", case: "none" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "The lamp is broken.",
                clozeParts: ["Die ", " ist kaputt."],
                clozeAnswers: ["Lampe"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-013"),
                wordType: "noun",
                german: "Licht",
                article: "das",
                plural: "Lichter",
                english: "light",
                exampleGerman: [
                    { text: "Kannst", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "du", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "das", case: "akkusativ" },
                    { text: " ", case: "none" },
                    { text: "Licht", case: "akkusativ" },
                    { text: " ", case: "none" },
                    { text: "anmachen", case: "verb" },
                    { text: "?", case: "none" }
                ],
                exampleEnglish: "Can you turn on the light?",
                clozeParts: ["Kannst du das ", " anmachen?"],
                clozeAnswers: ["Licht"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-017"),
                wordType: "noun",
                german: "Bild",
                article: "das",
                plural: "Bilder",
                english: "picture / image",
                exampleGerman: [
                    { text: "An", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "der", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "Wand", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "hängt", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "ein", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Bild", case: "nominativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "A picture hangs on the wall.",
                clozeParts: ["An der Wand hängt ein ", "."],
                clozeAnswers: ["Bild"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-018"),
                wordType: "noun",
                german: "Uhr",
                article: "die",
                plural: "Uhren",
                english: "clock / watch",
                exampleGerman: [
                    { text: "Die", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Uhr", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "hängt", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "an", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "der", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "Wand", case: "dativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "The clock hangs on the wall.",
                clozeParts: ["Die ", " hängt an der Wand."],
                clozeAnswers: ["Uhr"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-020"),
                wordType: "noun",
                german: "Schreibtisch",
                article: "der",
                plural: "Schreibtische",
                english: "desk",
                exampleGerman: [
                    { text: "Ich", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "mache", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "meine", case: "akkusativ" },
                    { text: " ", case: "none" },
                    { text: "Hausaufgaben", case: "akkusativ" },
                    { text: " ", case: "none" },
                    { text: "am", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "Schreibtisch", case: "dativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "I do my homework at the desk.",
                clozeParts: ["Ich mache meine Hausaufgaben am ", "."],
                clozeAnswers: ["Schreibtisch"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-033"),
                wordType: "noun",
                german: "Spiegel",
                article: "der",
                plural: "Spiegel",
                english: "mirror",
                exampleGerman: [
                    { text: "Der", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Spiegel", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "ist", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "im", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "Bad", case: "dativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "The mirror is in the bathroom.",
                clozeParts: ["Der ", " ist im Bad."],
                clozeAnswers: ["Spiegel"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-035"),
                wordType: "noun",
                german: "Gardine/Vorhang",
                article: "die",
                plural: "Gardinen/Vorhänge",
                english: "curtain",
                exampleGerman: [
                    { text: "Die", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Gardinen", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "sind", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "weiß", case: "none" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "The curtains are white.",
                clozeParts: ["Die ", " sind weiß."],
                clozeAnswers: ["Gardinen"]
            } as Noun
        ],

        // --- KATEGORIE 3: Haus, Geräte und Adresse (17 Vokabeln) ---
        "Haus, Geräte und Adresse": [
            {
                id: createWordId("wohnen-zimmer-019"),
                wordType: "noun",
                german: "Fernseher",
                article: "der",
                plural: "Fernseher",
                english: "television set",
                exampleGerman: [
                    { text: "Der", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Fernseher", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "ist", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "neu", case: "none" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "The television is new.",
                clozeParts: ["Der ", " ist neu."],
                clozeAnswers: ["Fernseher"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-021"),
                wordType: "noun",
                german: "Heizung",
                article: "die",
                plural: "Heizungen",
                english: "heating",
                exampleGerman: [
                    { text: "Die", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Heizung", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "ist", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "aus", case: "none" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "The heating is off.",
                clozeParts: ["Die ", " ist aus."],
                clozeAnswers: ["Heizung"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-023"),
                wordType: "noun",
                german: "Stock",
                article: "der",
                plural: "Stockwerke",
                english: "floor / storey",
                exampleGerman: [
                    { text: "Unsere", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Wohnung", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "ist", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "im", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "ersten", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "Stock", case: "dativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "Our apartment is on the first floor.",
                clozeParts: ["Unsere Wohnung ist im ersten ", "."],
                clozeAnswers: ["Stock"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-024"),
                wordType: "noun",
                german: "Wohnung",
                article: "die",
                plural: "Wohnungen",
                english: "apartment / flat",
                exampleGerman: [
                    { text: "Unsere", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Wohnung", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "ist", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "im", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "ersten", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "Stock", case: "dativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "Our apartment is on the first floor.",
                clozeParts: ["Unsere ", " ist im ersten Stock."],
                clozeAnswers: ["Wohnung"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-025"),
                wordType: "noun",
                german: "Haus",
                article: "das",
                plural: "Häuser",
                english: "house",
                exampleGerman: [
                    { text: "Unser", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Haus", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "ist", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "sehr", case: "none" },
                    { text: " ", case: "none" },
                    { text: "alt", case: "none" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "Our house is very old.",
                clozeParts: ["Unser ", " ist sehr alt."],
                clozeAnswers: ["Haus"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-030"),
                wordType: "noun",
                german: "Herd",
                article: "der",
                plural: "Herde",
                english: "stove / cooker",
                exampleGerman: [
                    { text: "Der", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Herd", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "ist", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "neu", case: "none" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "The stove is new.",
                clozeParts: ["Der ", " ist neu."],
                clozeAnswers: ["Herd"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-031"),
                wordType: "noun",
                german: "Kühlschrank",
                article: "der",
                plural: "Kühlschränke",
                english: "refrigerator",
                exampleGerman: [
                    { text: "Im", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "Kühlschrank", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "ist", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "Milch", case: "nominativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "There is milk in the refrigerator.",
                clozeParts: ["Im ", " ist Milch."],
                clozeAnswers: ["Kühlschrank"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-032"),
                wordType: "noun",
                german: "Waschmaschine",
                article: "die",
                plural: "Waschmaschinen",
                english: "washing machine",
                exampleGerman: [
                    { text: "Die", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Waschmaschine", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "ist", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "laut", case: "none" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "The washing machine is loud.",
                clozeParts: ["Die ", " ist laut."],
                clozeAnswers: ["Waschmaschine"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-038"),
                wordType: "noun",
                german: "Garage",
                article: "die",
                plural: "Garagen",
                english: "garage",
                exampleGerman: [
                    { text: "Das", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Auto", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "steht", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "in", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "der", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "Garage", case: "dativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "The car is in the garage.",
                clozeParts: ["Das Auto steht in der ", "."],
                clozeAnswers: ["Garage"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-039"),
                wordType: "noun",
                german: "Keller",
                article: "der",
                plural: "Keller",
                english: "basement / cellar",
                exampleGerman: [
                    { text: "Die", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Fahrräder", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "sind", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "im", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "Keller", case: "dativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "The bicycles are in the basement.",
                clozeParts: ["Die Fahrräder sind im ", "."],
                clozeAnswers: ["Keller"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-040"),
                wordType: "noun",
                german: "Schlüssel",
                article: "der",
                plural: "Schlüssel",
                english: "key",
                exampleGerman: [
                    { text: "Ich", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "habe", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "meinen", case: "akkusativ" },
                    { text: " ", case: "none" },
                    { text: "Schlüssel", case: "akkusativ" },
                    { text: " ", case: "none" },
                    { text: "verloren", case: "verb" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "I have lost my key.",
                clozeParts: ["Ich habe meinen ", " verloren."],
                clozeAnswers: ["Schlüssel"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-041"),
                wordType: "noun",
                german: "Adresse",
                article: "die",
                plural: "Adressen",
                english: "address",
                exampleGerman: [
                    { text: "Ich", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "weiß", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "die", case: "akkusativ" },
                    { text: " ", case: "none" },
                    { text: "Adresse", case: "akkusativ" },
                    { text: " ", case: "none" },
                    { text: "nicht", case: "none" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "I don't know the address.",
                clozeParts: ["Ich weiß die ", " nicht."],
                clozeAnswers: ["Adresse"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-042"),
                wordType: "noun",
                german: "Nummer",
                article: "die",
                plural: "Nummern",
                english: "number (house number)",
                exampleGerman: [
                    { text: "Meine", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Hausnummer", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "ist", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "12", case: "none" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "My house number is 12.",
                clozeParts: ["Meine Haus", " ist 12."],
                clozeAnswers: ["nummer"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-043"),
                wordType: "noun",
                german: "Straße",
                article: "die",
                plural: "Straßen",
                english: "street",
                exampleGerman: [
                    { text: "Ich", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "wohne", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "in", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "der", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "Bahnhofstraße", case: "dativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "I live on Bahnhofstraße.",
                clozeParts: ["Ich wohne in der ", "."],
                clozeAnswers: ["Bahnhofstraße"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-044"),
                wordType: "noun",
                german: "Stadt",
                article: "die",
                plural: "Städte",
                english: "city / town",
                exampleGerman: [
                    { text: "Ich", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "wohne", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "in", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "einer", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "kleinen", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "Stadt", case: "dativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "I live in a small town.",
                clozeParts: ["Ich wohne in einer kleinen ", "."],
                clozeAnswers: ["Stadt"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-045"),
                wordType: "noun",
                german: "Postleitzahl (PLZ)",
                article: "die",
                plural: "Postleitzahlen (PLZs)",
                english: "postal code / zip code",
                exampleGerman: [
                    { text: "Meine", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Postleitzahl", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "ist", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "80331", case: "none" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "My postal code is 80331.",
                clozeParts: ["Meine ", " ist 80331."],
                clozeAnswers: ["Postleitzahl"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-046"),
                wordType: "noun",
                german: "Nachbar/Nachbarin",
                article: "der/die",
                plural: "Nachbarn/Nachbarinnen",
                english: "neighbor (male/female)",
                exampleGerman: [
                    { text: "Mein", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Nachbar", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "ist", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "sehr", case: "none" },
                    { text: " ", case: "none" },
                    { text: "nett", case: "none" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "My neighbor is very nice.",
                clozeParts: ["Mein ", " ist sehr nett."],
                clozeAnswers: ["Nachbar"]
            } as Noun,
            {
                id: createWordId("wohnen-zimmer-047"),
                wordType: "noun",
                german: "Miete",
                article: "die",
                plural: "Mieten",
                english: "rent",
                exampleGerman: [
                    { text: "Die", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Miete", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "ist", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "teuer", case: "none" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "The rent is expensive.",
                clozeParts: ["Die ", " ist teuer."],
                clozeAnswers: ["Miete"]
            } as Noun
        ],

        // --- KATEGORIE 4: Garten (22 Vokabeln) ---
        "Garten": [
            {
                id: createWordId("wohnen-garten-001"),
                wordType: "noun",
                german: "Garten",
                article: "der",
                plural: "Gärten",
                english: "garden",
                exampleGerman: [
                    { text: "Wir", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "haben", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "einen", case: "akkusativ" },
                    { text: " ", case: "none" },
                    { text: "großen", case: "akkusativ" },
                    { text: " ", case: "none" },
                    { text: "Garten", case: "akkusativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "We have a large garden.",
                clozeParts: ["Wir haben einen großen ", "."],
                clozeAnswers: ["Garten"]
            } as Noun,
            {
                id: createWordId("wohnen-garten-002"),
                wordType: "noun",
                german: "Baum",
                article: "der",
                plural: "Bäume",
                english: "tree",
                exampleGerman: [
                    { text: "Die", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Bäume", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "sind", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "schon", case: "none" },
                    { text: " ", case: "none" },
                    { text: "grün", case: "none" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "The trees are already green.",
                clozeParts: ["Die ", " sind schon grün."],
                clozeAnswers: ["Bäume"]
            } as Noun,
            {
                id: createWordId("wohnen-garten-003"),
                wordType: "noun",
                german: "Blume",
                article: "die",
                plural: "Blumen",
                english: "flower",
                exampleGerman: [
                    { text: "Hier", case: "none" },
                    { text: " ", case: "none" },
                    { text: "sind", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "Blumen", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "für", case: "akkusativ" },
                    { text: " ", case: "none" },
                    { text: "dich", case: "akkusativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "Here are flowers for you.",
                clozeParts: ["Hier sind ", " für dich."],
                clozeAnswers: ["Blumen"]
            } as Noun,
            {
                id: createWordId("wohnen-garten-004"),
                wordType: "noun",
                german: "Gras",
                article: "das",
                plural: "Gräser",
                english: "grass",
                exampleGerman: [
                    { text: "Die", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Kinder", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "spielen", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "auf", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "dem", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "Gras", case: "dativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "The children are playing on the grass.",
                clozeParts: ["Die Kinder spielen auf dem ", "."],
                clozeAnswers: ["Gras"]
            } as Noun,
            {
                id: createWordId("wohnen-garten-005"),
                wordType: "noun",
                german: "Rasen",
                article: "der",
                plural: "Rasen",
                english: "lawn",
                exampleGerman: [
                    { text: "Der", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Rasen", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "ist", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "frisch", case: "none" },
                    { text: " ", case: "none" },
                    { text: "gemäht", case: "none" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "The lawn is freshly mown.",
                clozeParts: ["Der ", " ist frisch gemäht."],
                clozeAnswers: ["Rasen"]
            } as Noun,
            {
                id: createWordId("wohnen-garten-006"),
                wordType: "noun",
                german: "Busch",
                article: "der",
                plural: "Büsche",
                english: "bush",
                exampleGerman: [
                    { text: "Neben", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "dem", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "Haus", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "ist", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "ein", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Busch", case: "nominativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "There is a bush next to the house.",
                clozeParts: ["Neben dem Haus ist ein ", "."],
                clozeAnswers: ["Busch"]
            } as Noun,
            {
                id: createWordId("wohnen-garten-007"),
                wordType: "noun",
                german: "Hecke",
                article: "die",
                plural: "Hecken",
                english: "hedge",
                exampleGerman: [
                    { text: "Die", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Hecke", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "ist", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "hoch", case: "none" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "The hedge is high.",
                clozeParts: ["Die ", " ist hoch."],
                clozeAnswers: ["Hecke"]
            } as Noun,
            {
                id: createWordId("wohnen-garten-008"),
                wordType: "noun",
                german: "Zaun",
                article: "der",
                plural: "Zäune",
                english: "fence",
                exampleGerman: [
                    { text: "Der", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Zaun", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "ist", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "neu", case: "none" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "The fence is new.",
                clozeParts: ["Der ", " ist neu."],
                clozeAnswers: ["Zaun"]
            } as Noun,
            {
                id: createWordId("wohnen-garten-009"),
                wordType: "noun",
                german: "Terrasse",
                article: "die",
                plural: "Terrassen",
                english: "terrace / patio",
                exampleGerman: [
                    { text: "Wir", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "frühstücken", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "auf", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "der", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "Terrasse", case: "dativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "We have breakfast on the terrace.",
                clozeParts: ["Wir frühstücken auf der ", "."],
                clozeAnswers: ["Terrasse"]
            } as Noun,
            {
                id: createWordId("wohnen-garten-010"),
                wordType: "noun",
                german: "Hof",
                article: "der",
                plural: "Höfe",
                english: "courtyard / yard",
                exampleGerman: [
                    { text: "Die", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Kinder", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "spielen", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "im", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "Hof", case: "dativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "The children are playing in the yard.",
                clozeParts: ["Die Kinder spielen im ", "."],
                clozeAnswers: ["Hof"]
            } as Noun,
            {
                id: createWordId("wohnen-garten-011"),
                wordType: "noun",
                german: "Hund",
                article: "der",
                plural: "Hunde",
                english: "dog",
                exampleGerman: [
                    { text: "Ist", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "das", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "dein", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Hund", case: "nominativ" },
                    { text: "?", case: "none" }
                ],
                exampleEnglish: "Is that your dog?",
                clozeParts: ["Ist das dein ", "?"],
                clozeAnswers: ["Hund"]
            } as Noun,
            {
                id: createWordId("wohnen-garten-012"),
                wordType: "noun",
                german: "Katze",
                article: "die",
                plural: "Katzen",
                english: "cat",
                exampleGerman: [
                    { text: "Meine", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Katze", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "schläft", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "viel", case: "none" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "My cat sleeps a lot.",
                clozeParts: ["Meine ", " schläft viel."],
                clozeAnswers: ["Katze"]
            } as Noun,
            {
                id: createWordId("wohnen-garten-013"),
                wordType: "noun",
                german: "Vogel",
                article: "der",
                plural: "Vögel",
                english: "bird",
                exampleGerman: [
                    { text: "Im", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "Garten", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "singt", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "ein", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Vogel", case: "nominativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "A bird is singing in the garden.",
                clozeParts: ["Im Garten singt ein ", "."],
                clozeAnswers: ["Vogel"]
            } as Noun,
            {
                id: createWordId("wohnen-garten-014"),
                wordType: "verb",
                german: "spielen",
                english: "to play",
                separable: false,
                auxiliaryVerb: "haben",
                pastParticiple: "gespielt",
                presentConjugation: {
                    ich: "spiele",
                    du: "spielst",
                    er: "spielt",
                    wir: "spielen",
                    ihr: "spielt",
                    sie: "spielen"
                },
                imperative: {
                    du: "Spiel!",
                    ihr: "Spielt!",
                    Sie: "Spielen Sie!"
                },
                exampleGerman: [
                    { text: "Die", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Kinder", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "spielen", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "im", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "Garten", case: "dativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "The children are playing in the garden.",
                clozeParts: ["Die Kinder ", " im Garten."],
                clozeAnswers: ["spielen"]
            } as Verb,
            {
                id: createWordId("wohnen-garten-015"),
                wordType: "verb",
                german: "gießen",
                english: "to water (plants)",
                separable: false,
                auxiliaryVerb: "haben",
                pastParticiple: "gegossen",
                presentConjugation: {
                    ich: "gieße",
                    du: "gießt",
                    er: "gießt",
                    wir: "gießen",
                    ihr: "gießt",
                    sie: "gießen"
                },
                imperative: {
                    du: "Gieß!",
                    ihr: "Gießt!",
                    Sie: "Gießen Sie!"
                },
                exampleGerman: [
                    { text: "Ich", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "gieße", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "die", case: "akkusativ" },
                    { text: " ", case: "none" },
                    { text: "Blumen", case: "akkusativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "I am watering the flowers.",
                clozeParts: ["Ich ", " die Blumen."],
                clozeAnswers: ["gieße"]
            } as Verb,
            {
                id: createWordId("wohnen-garten-016"),
                wordType: "verb",
                german: "pflanzen",
                english: "to plant",
                separable: false,
                auxiliaryVerb: "haben",
                pastParticiple: "gepflanzt",
                presentConjugation: {
                    ich: "pflanze",
                    du: "pflanzt",
                    er: "pflanzt",
                    wir: "pflanzen",
                    ihr: "pflanzt",
                    sie: "pflanzen"
                },
                imperative: {
                    du: "Pflanz!",
                    ihr: "Pflanzt!",
                    Sie: "Pflanzen Sie!"
                },
                exampleGerman: [
                    { text: "Wir", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "pflanzen", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "einen", case: "akkusativ" },
                    { text: " ", case: "none" },
                    { text: "Baum", case: "akkusativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "We are planting a tree.",
                clozeParts: ["Wir ", " einen Baum."],
                clozeAnswers: ["pflanzen"]
            } as Verb,
            {
                id: createWordId("wohnen-garten-017"),
                wordType: "verb",
                german: "sitzen",
                english: "to sit",
                separable: false,
                auxiliaryVerb: "haben",
                pastParticiple: "gesessen",
                presentConjugation: {
                    ich: "sitze",
                    du: "sitzt",
                    er: "sitzt",
                    wir: "sitzen",
                    ihr: "sitzt",
                    sie: "sitzen"
                },
                imperative: {
                    du: "Sitz!",
                    ihr: "Sitzt!",
                    Sie: "Sitzen Sie!"
                },
                exampleGerman: [
                    { text: "Wir", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "sitzen", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "im", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "Garten", case: "dativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "We are sitting in the garden.",
                clozeParts: ["Wir ", " im Garten."],
                clozeAnswers: ["sitzen"]
            } as Verb,
            {
                id: createWordId("wohnen-garten-018"),
                wordType: "verb",
                german: "grillen",
                english: "to grill / to barbecue",
                separable: false,
                auxiliaryVerb: "haben",
                pastParticiple: "gegrillt",
                presentConjugation: {
                    ich: "grille",
                    du: "grillst",
                    er: "grillt",
                    wir: "grillen",
                    ihr: "grillt",
                    sie: "grillen"
                },
                imperative: {
                    du: "Grill!",
                    ihr: "Grillt!",
                    Sie: "Grillen Sie!"
                },
                exampleGerman: [
                    { text: "Im", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "Sommer", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "grillen", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "wir", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "im", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "Garten", case: "dativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "In summer we grill in the garden.",
                clozeParts: ["Im Sommer ", " wir im Garten."],
                clozeAnswers: ["grillen"]
            } as Verb,
            {
                id: createWordId("wohnen-garten-019"),
                wordType: "noun",
                german: "Sonne",
                article: "die",
                plural: "Sonnen",
                english: "sun",
                exampleGerman: [
                    { text: "Die", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Sonne", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "scheint", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "im", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "Garten", case: "dativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "The sun is shining in the garden.",
                clozeParts: ["Die ", " scheint im Garten."],
                clozeAnswers: ["Sonne"]
            } as Noun,
            {
                id: createWordId("wohnen-garten-020"),
                wordType: "noun",
                german: "Schatten",
                article: "der",
                plural: "Schatten",
                english: "shade / shadow",
                exampleGerman: [
                    { text: "Im", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "Schatten", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "ist", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "es", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "kühl", case: "none" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "It is cool in the shade.",
                clozeParts: ["Im ", " ist es kühl."],
                clozeAnswers: ["Schatten"]
            } as Noun,
            {
                id: createWordId("wohnen-garten-021"),
                wordType: "noun",
                german: "Werkzeug",
                article: "das",
                plural: "Werkzeuge",
                english: "tool / tools",
                exampleGerman: [
                    { text: "Das", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Werkzeug", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "liegt", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "im", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "Gartenhaus", case: "dativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "The tools are in the garden shed.",
                clozeParts: ["Das ", " liegt im Gartenhaus."],
                clozeAnswers: ["Werkzeug"]
            } as Noun,
            {
                id: createWordId("wohnen-garten-022"),
                wordType: "noun",
                german: "Gartenhaus",
                article: "das",
                plural: "Gartenhäuser",
                english: "garden shed / summer house",
                exampleGerman: [
                    { text: "Das", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "Werkzeug", case: "nominativ" },
                    { text: " ", case: "none" },
                    { text: "liegt", case: "verb" },
                    { text: " ", case: "none" },
                    { text: "im", case: "dativ" },
                    { text: " ", case: "none" },
                    { text: "Gartenhaus", case: "dativ" },
                    { text: ".", case: "none" }
                ],
                exampleEnglish: "The tools are in the garden shed.",
                clozeParts: ["Das Werkzeug liegt im ", "."],
                clozeAnswers: ["Gartenhaus"]
            } as Noun
        ]
    }
});
