// packages/trainer-themen/vokabular_lernen.js

export const vokabularLernen = {
    "Lernen": {

        // --- NEUE KATEGORIE 1: Orte, Personen & Fächer ---
        "Orte, Personen & Fächer": [
            {
                id: "lernen-schuleunterricht-001",
                wortart: "Nomen",
                german: "Schule",
                artikel: "die",
                plural: "Schulen",
                english: "school",
                example_de: [{ "text": "Wir", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "haben", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "bis ein Uhr", "kasus": "none" }, { "text": " ", "kasus": "none" }, { "text": "Unterricht", "kasus": "akkusativ" }, { "text": ".", "kasus": "none" }],
                example_en: "We have lessons until one o'clock.",
                cloze_parts: ["Wir haben bis ein Uhr ", "."],
                cloze_answers: ["Unterricht"]
            },
            {
                id: "lernen-schuleunterricht-002",
                wortart: "Nomen",
                german: "Unterricht",
                artikel: "der",
                plural: null,
                english: "lesson(s) / class",
                example_de: [{ "text": "Wir", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "haben", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "bis ein Uhr", "kasus": "none" }, { "text": " ", "kasus": "none" }, { "text": "Unterricht", "kasus": "akkusativ" }, { "text": ".", "kasus": "none" }],
                example_en: "We have lessons until one o'clock.",
                cloze_parts: ["Wir haben bis ein Uhr ", "."],
                cloze_answers: ["Unterricht"]
            },
            {
                id: "lernen-schuleunterricht-003",
                wortart: "Nomen",
                german: "Lehrer/Lehrerin",
                artikel: "der/die",
                plural: "Lehrer/Lehrerinnen",
                english: "teacher (male/female)",
                example_de: [{ "text": "Der Lehrer", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "ist", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "freundlich", "kasus": "none" }, { "text": ".", "kasus": "none" }],
                example_en: "The teacher is friendly.",
                cloze_parts: ["Der ", " ist freundlich."],
                cloze_answers: ["Lehrer"]
            },
            {
                id: "lernen-schuleunterricht-004",
                wortart: "Nomen",
                german: "Schüler/Schülerin",
                artikel: "der/die",
                plural: "Schüler/Schülerinnen",
                english: "student (male/female)",
                example_de: [{ "text": "Die Schüler", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "sind", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "freundlich", "kasus": "none" }, { "text": ".", "kasus": "none" }],
                example_en: "The students are friendly.",
                cloze_parts: ["Die ", " sind freundlich."],
                cloze_answers: ["Schüler"]
            },
            {
                id: "lernen-schuleunterricht-005",
                wortart: "Nomen",
                german: "Klasse",
                artikel: "die",
                plural: "Klassen",
                english: "class",
                example_de: [{ "text": "In unserer Klasse", "kasus": "dativ" }, { "text": " ", "kasus": "none" }, { "text": "sind", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "20 Schüler", "kasus": "nominativ" }, { "text": ".", "kasus": "none" }],
                example_en: "There are 20 students in our class.",
                cloze_parts: ["In unserer ", " sind 20 Schüler."],
                cloze_answers: ["Klasse"]
            },
            {
                id: "lernen-schuleunterricht-024",
                wortart: "Nomen",
                german: "Schulfach",
                artikel: "das",
                plural: "Schulfächer",
                english: "school subject",
                example_de: [{ "text": "Chemie", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "ist", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "mein Lieblingsfach", "kasus": "nominativ" }, { "text": ".", "kasus": "none" }],
                example_en: "Chemistry is my favorite subject.",
                cloze_parts: ["Chemie ist mein Lieblings", "."],
                cloze_answers: ["fach"]
            },
            {
                id: "lernen-schuleunterricht-025",
                wortart: "Nomen",
                german: "Gymnasium",
                artikel: "das",
                plural: "Gymnasien",
                english: "grammar school / high school",
                example_de: [{ "text": "Ich", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "gehe", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "aufs Gymnasium", "kasus": "akkusativ" }, { "text": ".", "kasus": "none" }],
                example_en: "I go to grammar school.",
                cloze_parts: ["Ich gehe aufs ", "."],
                cloze_answers: ["Gymnasium"]
            },
            {
                id: "lernen-schuleunterricht-026",
                wortart: "Nomen",
                german: "Sprachenschule",
                artikel: "die",
                plural: "Sprachenschulen",
                english: "language school",
                example_de: [{ "text": "Ich", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "lerne", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "Deutsch", "kasus": "akkusativ" }, { "text": " ", "kasus": "none" }, { "text": "in der Sprachenschule", "kasus": "dativ" }, { "text": ".", "kasus": "none" }],
                example_en: "I learn German at the language school.",
                cloze_parts: ["Ich lerne Deutsch in der ", "."],
                cloze_answers: ["Sprachenschule"]
            },
            {
                id: "lernen-schuleunterricht-027",
                wortart: "Nomen",
                german: "Goethe-Institut",
                artikel: "das",
                plural: "Goethe-Institute",
                english: "Goethe-Institut",
                example_de: [{ "text": "Ich", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "mache", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "einen Kurs", "kasus": "akkusativ" }, { "text": " ", "kasus": "none" }, { "text": "am Goethe-Institut", "kasus": "dativ" }, { "text": ".", "kasus": "none" }],
                example_en: "I am taking a course at the Goethe-Institut.",
                cloze_parts: ["Ich mache einen Kurs am ", "."],
                cloze_answers: ["Goethe-Institut"]
            },
            {
                id: "lernen-schuleunterricht-028",
                wortart: "Nomen",
                german: "Sozialkunde",
                artikel: "die",
                plural: null,
                english: "social studies",
                example_de: [{ "text": "Sozialkunde", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "ist", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "interessant", "kasus": "none" }, { "text": ".", "kasus": "none" }],
                example_en: "Social studies is interesting.",
                cloze_parts: ["", " ist interessant."],
                cloze_answers: ["Sozialkunde"]
            },
            {
                id: "lernen-schuleunterricht-029",
                wortart: "Nomen",
                german: "Kunst",
                artikel: "die",
                plural: "Künste",
                english: "art",
                example_de: [{ "text": "Ich", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "mag", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "Kunst", "kasus": "akkusativ" }, { "text": ".", "kasus": "none" }],
                example_en: "I like art.",
                cloze_parts: ["Ich mag ", "."],
                cloze_answers: ["Kunst"]
            },
            {
                id: "lernen-schuleunterricht-030",
                wortart: "Nomen",
                german: "Sport",
                artikel: "der",
                plural: null,
                english: "sports / P.E.",
                example_de: [{ "text": "Sport", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "ist", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "mein Lieblingsfach", "kasus": "nominativ" }, { "text": ".", "kasus": "none" }],
                example_en: "Sports is my favorite subject.",
                cloze_parts: ["", " ist mein Lieblingsfach."],
                cloze_answers: ["Sport"]
            },
            {
                id: "lernen-schuleunterricht-031",
                wortart: "Nomen",
                german: "Physik",
                artikel: "die",
                plural: null,
                english: "physics",
                example_de: [{ "text": "Physik", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "ist", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "schwer", "kasus": "none" }, { "text": ".", "kasus": "none" }],
                example_en: "Physics is difficult.",
                cloze_parts: ["", " ist schwer."],
                cloze_answers: ["Physik"]
            },
            {
                id: "lernen-schuleunterricht-032",
                wortart: "Nomen",
                german: "Chemie",
                artikel: "die",
                plural: null,
                english: "chemistry",
                example_de: [{ "text": "Chemie", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "ist", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "mein Lieblingsfach", "kasus": "nominativ" }, { "text": ".", "kasus": "none" }],
                example_en: "Chemistry is my favorite subject.",
                cloze_parts: ["", " ist mein Lieblingsfach."],
                cloze_answers: ["Chemie"]
            },
            {
                id: "lernen-schuleunterricht-033",
                wortart: "Nomen",
                german: "Geschichte",
                artikel: "die",
                plural: "Geschichten",
                english: "history",
                example_de: [{ "text": "Geschichte", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "ist", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "spannend", "kasus": "none" }, { "text": ".", "kasus": "none" }],
                example_en: "History is exciting.",
                cloze_parts: ["", " ist spannend."],
                cloze_answers: ["Geschichte"]
            },
            {
                id: "lernen-schuleunterricht-034",
                wortart: "Nomen",
                german: "Geografie",
                artikel: "die",
                plural: null,
                english: "geography",
                example_de: [{ "text": "Geografie", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "finde", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "ich", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "toll", "kasus": "none" }, { "text": ".", "kasus": "none" }],
                example_en: "I find geography great.",
                cloze_parts: ["", " finde ich toll."],
                cloze_answers: ["Geografie"]
            },
            {
                id: "lernen-schuleunterricht-035",
                wortart: "Nomen",
                german: "Mathematik",
                artikel: "die",
                plural: null,
                english: "mathematics",
                example_de: [{ "text": "Mathematik", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "ist", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "schwierig", "kasus": "none" }, { "text": ".", "kasus": "none" }],
                example_en: "Mathematics is difficult.",
                cloze_parts: ["", " ist schwierig."],
                cloze_answers: ["Mathematik"]
            },
            {
                id: "lernen-schuleunterricht-036",
                wortart: "Nomen",
                german: "Englisch",
                artikel: "das",
                plural: null,
                english: "English",
                example_de: [{ "text": "Englisch", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "ist", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "einfach", "kasus": "none" }, { "text": ".", "kasus": "none" }],
                example_en: "English is easy.",
                cloze_parts: ["", " ist einfach."],
                cloze_answers: ["Englisch"]
            },
            {
                id: "lernen-schuleunterricht-037",
                wortart: "Nomen",
                german: "Deutsch",
                artikel: "das",
                plural: null,
                english: "German",
                example_de: [{ "text": "Wir", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "lernen", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "Deutsch", "kasus": "akkusativ" }, { "text": ".", "kasus": "none" }],
                example_en: "We are learning German.",
                cloze_parts: ["Wir lernen ", "."],
                cloze_answers: ["Deutsch"]
            }
        ],

        // --- NEUE KATEGORIE 2: Materialien & Aufgaben ---
        "Materialien & Aufgaben": [
            {
                id: "lernen-schuleunterricht-006",
                wortart: "Nomen",
                german: "Hausaufgabe",
                artikel: "die",
                plural: "Hausaufgaben",
                english: "homework",
                example_de: [{ "text": "Die Hausaufgaben", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "sind", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "einfach", "kasus": "none" }, { "text": ".", "kasus": "none" }],
                example_en: "The homework is easy.",
                cloze_parts: ["Die ", " sind einfach."],
                cloze_answers: ["Hausaufgaben"]
            },
            {
                id: "lernen-schuleunterricht-007",
                wortart: "Nomen",
                german: "Aufgabe",
                artikel: "die",
                plural: "Aufgaben",
                english: "task / exercise",
                example_de: [{ "text": "Die Aufgabe", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "ist", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "einfach", "kasus": "none" }, { "text": ".", "kasus": "none" }],
                example_en: "The task is easy.",
                cloze_parts: ["Die ", " ist einfach."],
                cloze_answers: ["Aufgabe"]
            },
            {
                id: "lernen-schuleunterricht-008",
                wortart: "Nomen",
                german: "Übung",
                artikel: "die",
                plural: "Übungen",
                english: "exercise / practice",
                example_de: [{ "text": "Die Übung", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "ist", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "ganz einfach", "kasus": "none" }, { "text": ".", "kasus": "none" }],
                example_en: "The exercise is very easy.",
                cloze_parts: ["Die ", " ist ganz einfach."],
                cloze_answers: ["Übung"]
            },
            {
                id: "lernen-schuleunterricht-009",
                wortart: "Nomen",
                german: "Tafel",
                artikel: "die",
                plural: "Tafeln",
                english: "blackboard / whiteboard",
                example_de: [{ "text": "Die Tafel", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "ist", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "grün", "kasus": "none" }, { "text": ".", "kasus": "none" }],
                example_en: "The blackboard is green.",
                cloze_parts: ["Die ", " ist grün."],
                cloze_answers: ["Tafel"]
            },
            {
                id: "lernen-schuleunterricht-010",
                wortart: "Nomen",
                german: "Heft",
                artikel: "das",
                plural: "Hefte",
                english: "notebook",
                example_de: [{ "text": "Ich", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "brauche", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "ein neues Heft", "kasus": "akkusativ" }, { "text": ".", "kasus": "none" }],
                example_en: "I need a new notebook.",
                cloze_parts: ["Ich brauche ein neues ", "."],
                cloze_answers: ["Heft"]
            },
            {
                id: "lernen-schuleunterricht-011",
                wortart: "Nomen",
                german: "Buch",
                artikel: "das",
                plural: "Bücher",
                english: "book",
                example_de: [{ "text": "Die Bücher", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "sind", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "schon", "kasus": "none" }, { "text": " ", "kasus": "none" }, { "text": "im Rucksack", "kasus": "dativ" }, { "text": ".", "kasus": "none" }],
                example_en: "The books are already in the backpack.",
                cloze_parts: ["Die ", " sind schon im Rucksack."],
                cloze_answers: ["Bücher"]
            },
            {
                id: "lernen-schuleunterricht-012",
                wortart: "Nomen",
                german: "Wörterbuch",
                artikel: "das",
                plural: "Wörterbücher",
                english: "dictionary",
                example_de: [{ "text": "Ich", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "brauche", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "ein Wörterbuch", "kasus": "akkusativ" }, { "text": ".", "kasus": "none" }],
                example_en: "I need a dictionary.",
                cloze_parts: ["Ich brauche ein ", "."],
                cloze_answers: ["Wörterbuch"]
            },
            {
                id: "lernen-schuleunterricht-013",
                wortart: "Nomen",
                german: "Stift",
                artikel: "der",
                plural: "Stifte",
                english: "pen",
                example_de: [{ "text": "Ich", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "schreibe", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "mit dem Stift", "kasus": "dativ" }, { "text": ".", "kasus": "none" }],
                example_en: "I write with the pen.",
                cloze_parts: ["Ich schreibe mit dem ", "."],
                cloze_answers: ["Stift"]
            },
            {
                id: "lernen-schuleunterricht-014",
                wortart: "Nomen",
                german: "Bleistift",
                artikel: "der",
                plural: "Bleistifte",
                english: "pencil",
                example_de: [{ "text": "Hier", "kasus": "none" }, { "text": " ", "kasus": "none" }, { "text": "ist", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "dein Bleistift", "kasus": "nominativ" }, { "text": ".", "kasus": "none" }],
                example_en: "Here is your pencil.",
                cloze_parts: ["Hier ist dein ", "."],
                cloze_answers: ["Bleistift"]
            },
            {
                id: "lernen-schuleunterricht-015",
                wortart: "Nomen",
                german: "Radiergummi",
                artikel: "der",
                plural: "Radiergummis",
                english: "eraser",
                example_de: [{ "text": "Ich", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "habe", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "meinen Radiergummi", "kasus": "akkusativ" }, { "text": " ", "kasus": "none" }, { "text": "vergessen", "kasus": "verb" }, { "text": ".", "kasus": "none" }],
                example_en: "I have forgotten my eraser.",
                cloze_parts: ["Ich habe meinen ", " vergessen."],
                cloze_answers: ["Radiergummi"]
            },
            {
                id: "lernen-schuleunterricht-016",
                wortart: "Nomen",
                german: "Lineal",
                artikel: "das",
                plural: "Lineale",
                english: "ruler",
                example_de: [{ "text": "Das Lineal", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "ist", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "lang", "kasus": "none" }, { "text": ".", "kasus": "none" }],
                example_en: "The ruler is long.",
                cloze_parts: ["Das ", " ist lang."],
                cloze_answers: ["Lineal"]
            },
            {
                id: "lernen-schuleunterricht-017",
                wortart: "Nomen",
                german: "Schere",
                artikel: "die",
                plural: "Scheren",
                english: "scissors",
                example_de: [{ "text": "Die Schere", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "ist", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "scharf", "kasus": "none" }, { "text": ".", "kasus": "none" }],
                example_en: "The scissors are sharp.",
                cloze_parts: ["Die ", " ist scharf."],
                cloze_answers: ["Schere"]
            },
            {
                id: "lernen-schuleunterricht-018",
                wortart: "Nomen",
                german: "Mappe",
                artikel: "die",
                plural: "Mappen",
                english: "folder",
                example_de: [{ "text": "Die Mappe", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "ist", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "blau", "kasus": "none" }, { "text": ".", "kasus": "none" }],
                example_en: "The folder is blue.",
                cloze_parts: ["Die ", " ist blau."],
                cloze_answers: ["Mappe"]
            },
            {
                id: "lernen-schuleunterricht-019",
                wortart: "Nomen",
                german: "Papier",
                artikel: "das",
                plural: "Papiere",
                english: "paper",
                example_de: [{ "text": "Ich", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "brauche", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "Papier", "kasus": "akkusativ" }, { "text": ".", "kasus": "none" }],
                example_en: "I need paper.",
                cloze_parts: ["Ich brauche ", "."],
                cloze_answers: ["Papier"]
            },
            {
                id: "lernen-schuleunterricht-020",
                wortart: "Nomen",
                german: "Rucksack",
                artikel: "der",
                plural: "Rucksäcke",
                english: "backpack",
                example_de: [{ "text": "Mein Rucksack", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "ist", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "schwer", "kasus": "none" }, { "text": ".", "kasus": "none" }],
                example_en: "My backpack is heavy.",
                cloze_parts: ["Mein ", " ist schwer."],
                cloze_answers: ["Rucksack"]
            },
            {
                id: "lernen-schuleunterricht-021",
                wortart: "Nomen",
                german: "Tasche",
                artikel: "die",
                plural: "Taschen",
                english: "bag",
                example_de: [{ "text": "Die Tasche", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "steht", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "auf dem Boden", "kasus": "dativ" }, { "text": ".", "kasus": "none" }],
                example_en: "The bag is on the floor.",
                cloze_parts: ["Die ", " steht auf dem Boden."],
                cloze_answers: ["Tasche"]
            },
            {
                id: "lernen-schuleunterricht-022",
                wortart: "Nomen",
                german: "Pause",
                artikel: "die",
                plural: "Pausen",
                english: "break / recess",
                example_de: [{ "text": "In der Pause", "kasus": "dativ" }, { "text": " ", "kasus": "none" }, { "text": "spielen", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "wir", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "Fußball", "kasus": "akkusativ" }, { "text": ".", "kasus": "none" }],
                example_en: "During the break, we play football.",
                cloze_parts: ["In der ", " spielen wir Fußball."],
                cloze_answers: ["Pause"]
            },
            {
                id: "lernen-schuleunterricht-023",
                wortart: "Nomen",
                german: "Stundenplan",
                artikel: "der",
                plural: "Stundenpläne",
                english: "timetable / schedule",
                example_de: [{ "text": "Mein Stundenplan", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "ist", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "voll", "kasus": "none" }, { "text": ".", "kasus": "none" }],
                example_en: "My timetable is full.",
                cloze_parts: ["Mein ", " ist voll."],
                cloze_answers: ["Stundenplan"]
            }
        ],

        // --- NEUE KATEGORIE 3: Verben des Lernens ---
        "Verben des Lernens": [
            {
                id: "lernen-sprachenlernen-001",
                wortart: "Verb",
                german: "lernen",
                english: "to learn",
                trennbar: false,
                hilfsverb_perfekt: "haben",
                partizip_ii: "gelernt",
                konjugation_praesens: { ich: "lerne", du: "lernst", er_sie_es: "lernt", wir: "lernen", ihr: "lernt", sie_Sie: "lernen" },
                imperativ: { du: "Lern!", ihr: "Lernt!" },
                example_de: [{ "text": "Wir", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "lernen", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "Deutsch", "kasus": "akkusativ" }, { "text": ".", "kasus": "none" }],
                example_en: "We are learning German.",
                cloze_parts: ["Wir ", " Deutsch."],
                cloze_answers: ["lernen"]
            },
            {
                id: "lernen-sprachenlernen-002",
                wortart: "Verb",
                german: "üben",
                english: "to practice",
                trennbar: false,
                hilfsverb_perfekt: "haben",
                partizip_ii: "geübt",
                konjugation_praesens: { ich: "übe", du: "übst", er_sie_es: "übt", wir: "üben", ihr: "übt", sie_Sie: "üben" },
                imperativ: { du: "Üb!", ihr: "Übt!" },
                example_de: [{ "text": "Ich", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "übe", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "jeden Tag", "kasus": "akkusativ" }, { "text": " ", "kasus": "none" }, { "text": "Deutsch", "kasus": "akkusativ" }, { "text": ".", "kasus": "none" }],
                example_en: "I practice German every day.",
                cloze_parts: ["Ich ", " jeden Tag Deutsch."],
                cloze_answers: ["übe"]
            },
            {
                id: "lernen-sprachenlernen-003",
                wortart: "Verb",
                german: "sprechen",
                english: "to speak",
                trennbar: false,
                hilfsverb_perfekt: "haben",
                partizip_ii: "gesprochen",
                konjugation_praesens: { ich: "spreche", du: "sprichst", er_sie_es: "spricht", wir: "sprechen", ihr: "sprecht", sie_Sie: "sprechen" },
                imperativ: { du: "Sprich!", ihr: "Sprecht!" },
                example_de: [{ "text": "Ich", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "spreche", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "ein bisschen", "kasus": "none" }, { "text": " ", "kasus": "none" }, { "text": "Deutsch", "kasus": "akkusativ" }, { "text": ".", "kasus": "none" }],
                example_en: "I speak a little German.",
                cloze_parts: ["Ich ", " ein bisschen Deutsch."],
                cloze_answers: ["spreche"]
            },
            {
                id: "lernen-sprachenlernen-004",
                wortart: "Verb",
                german: "lesen",
                english: "to read",
                trennbar: false,
                hilfsverb_perfekt: "haben",
                partizip_ii: "gelesen",
                konjugation_praesens: { ich: "lese", du: "liest", er_sie_es: "liest", wir: "lesen", ihr: "lest", sie_Sie: "lesen" },
                imperativ: { du: "Lies!", ihr: "Lest!" },
                example_de: [{ "text": "Ich", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "lese", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "ein Buch", "kasus": "akkusativ" }, { "text": ".", "kasus": "none" }],
                example_en: "I am reading a book.",
                cloze_parts: ["Ich ", " ein Buch."],
                cloze_answers: ["lese"]
            },
            {
                id: "lernen-sprachenlernen-005",
                wortart: "Verb",
                german: "schreiben",
                english: "to write",
                trennbar: false,
                hilfsverb_perfekt: "haben",
                partizip_ii: "geschrieben",
                konjugation_praesens: { ich: "schreibe", du: "schreibst", er_sie_es: "schreibt", wir: "schreiben", ihr: "schreibt", sie_Sie: "schreiben" },
                imperativ: { du: "Schreib!", ihr: "Schreibt!" },
                example_de: [{ "text": "Ich", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "schreibe", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "einen Brief", "kasus": "akkusativ" }, { "text": ".", "kasus": "none" }],
                example_en: "I am writing a letter.",
                cloze_parts: ["Ich ", " einen Brief."],
                cloze_answers: ["schreibe"]
            },
            {
                id: "lernen-sprachenlernen-006",
                wortart: "Verb",
                german: "verstehen",
                english: "to understand",
                trennbar: false,
                hilfsverb_perfekt: "haben",
                partizip_ii: "verstanden",
                konjugation_praesens: { ich: "verstehe", du: "verstehst", er_sie_es: "versteht", wir: "verstehen", ihr: "versteht", sie_Sie: "verstehen" },
                imperativ: { du: "Versteh!", ihr: "Versteht!" },
                example_de: [{ "text": "Ich", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "verstehe", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "die Frage", "kasus": "akkusativ" }, { "text": " ", "kasus": "none" }, { "text": "nicht", "kasus": "none" }, { "text": ".", "kasus": "none" }],
                example_en: "I don't understand the question.",
                cloze_parts: ["Ich ", " die Frage nicht."],
                cloze_answers: ["verstehe"]
            },
            {
                id: "lernen-sprachenlernen-007",
                wortart: "Verb",
                german: "wiederholen",
                english: "to repeat",
                trennbar: false,
                hilfsverb_perfekt: "haben",
                partizip_ii: "wiederholt",
                konjugation_praesens: { ich: "wiederhole", du: "wiederholst", er_sie_es: "wiederholt", wir: "wiederholen", ihr: "wiederholt", sie_Sie: "wiederholen" },
                imperativ: { du: "Wiederhol!", ihr: "Wiederholt!" },
                example_de: [{ "text": "Kannst", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "du", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "das", "kasus": "akkusativ" }, { "text": " ", "kasus": "none" }, { "text": "bitte", "kasus": "none" }, { "text": " ", "kasus": "none" }, { "text": "wiederholen", "kasus": "verb" }, { "text": "?", "kasus": "none" }],
                example_en: "Can you please repeat that?",
                cloze_parts: ["Kannst du das bitte ", "?"],
                cloze_answers: ["wiederholen"]
            },
            {
                id: "lernen-sprachenlernen-008",
                wortart: "Verb",
                german: "fragen",
                english: "to ask",
                trennbar: false,
                hilfsverb_perfekt: "haben",
                partizip_ii: "gefragt",
                konjugation_praesens: { ich: "frage", du: "fragst", er_sie_es: "fragt", wir: "fragen", ihr: "fragt", sie_Sie: "fragen" },
                imperativ: { du: "Frag!", ihr: "Fragt!" },
                example_de: [{ "text": "Ich", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "möchte", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "etwas", "kasus": "akkusativ" }, { "text": " ", "kasus": "none" }, { "text": "fragen", "kasus": "verb" }, { "text": ".", "kasus": "none" }],
                example_en: "I would like to ask something.",
                cloze_parts: ["Ich möchte etwas ", "."],
                cloze_answers: ["fragen"]
            },
            {
                id: "lernen-sprachenlernen-009",
                wortart: "Verb",
                german: "antworten",
                english: "to answer",
                trennbar: false,
                hilfsverb_perfekt: "haben",
                partizip_ii: "geantwortet",
                konjugation_praesens: { ich: "antworte", du: "antwortest", er_sie_es: "antwortet", wir: "antworten", ihr: "antwortet", sie_Sie: "antworten" },
                imperativ: { du: "Antworte!", ihr: "Antwortet!" },
                example_de: [{ "text": "Weißt", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "du", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "die Antwort", "kasus": "akkusativ" }, { "text": "?", "kasus": "none" }],
                example_en: "Do you know the answer?",
                cloze_parts: ["Weißt du die ", "?"],
                cloze_answers: ["Antwort"]
            },
            {
                id: "lernen-sprachenlernen-010",
                wortart: "Verb",
                german: "erklären",
                english: "to explain",
                trennbar: false,
                hilfsverb_perfekt: "haben",
                partizip_ii: "erklärt",
                konjugation_praesens: { ich: "erkläre", du: "erklärst", er_sie_es: "erklärt", wir: "erklären", ihr: "erklärt", sie_Sie: "erklären" },
                imperativ: { du: "Erklär!", ihr: "Erklärt!" },
                example_de: [{ "text": "Können", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "Sie", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "das", "kasus": "akkusativ" }, { "text": " ", "kasus": "none" }, { "text": "bitte", "kasus": "none" }, { "text": " ", "kasus": "none" }, { "text": "erklären", "kasus": "verb" }, { "text": "?", "kasus": "none" }],
                example_en: "Can you please explain that?",
                cloze_parts: ["Können Sie das bitte ", "?"],
                cloze_answers: ["erklären"]
            },
            {
                id: "lernen-sprachenlernen-015",
                wortart: "Verb",
                german: "markieren",
                english: "to mark / to highlight",
                trennbar: false,
                hilfsverb_perfekt: "haben",
                partizip_ii: "markiert",
                konjugation_praesens: { ich: "markiere", du: "markierst", er_sie_es: "markiert", wir: "markieren", ihr: "markiert", sie_Sie: "markieren" },
                imperativ: { du: "Markier!", ihr: "Markiert!" },
                example_de: [{ "text": "Markiere", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "die richtige Antwort", "kasus": "akkusativ" }, { "text": ".", "kasus": "none" }],
                example_en: "Mark the correct answer.",
                cloze_parts: ["", " die richtige Antwort."],
                cloze_answers: ["Markiere"]
            },
            {
                id: "lernen-sprachenlernen-016",
                wortart: "Verb",
                german: "ergänzen",
                english: "to complete / to fill in",
                trennbar: false,
                hilfsverb_perfekt: "haben",
                partizip_ii: "ergänzt",
                konjugation_praesens: { ich: "ergänze", du: "ergänzt", er_sie_es: "ergänzt", wir: "ergänzen", ihr: "ergänzt", sie_Sie: "ergänzen" },
                imperativ: { du: "Ergänz!", ihr: "Ergänzt!" },
                example_de: [{ "text": "Ergänzen Sie", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "die Sätze", "kasus": "akkusativ" }, { "text": ".", "kasus": "none" }],
                example_en: "Complete the sentences.",
                cloze_parts: ["", " Sie die Sätze."],
                cloze_answers: ["Ergänzen"]
            },
            {
                id: "lernen-sprachenlernen-017",
                wortart: "Verb",
                german: "zuordnen",
                english: "to match / to assign",
                trennbar: true,
                hilfsverb_perfekt: "haben",
                partizip_ii: "zugeordnet",
                konjugation_praesens: { ich: "ordne zu", du: "ordnest zu", er_sie_es: "ordnet zu", wir: "ordnen zu", ihr: "ordnet zu", sie_Sie: "ordnen zu" },
                imperativ: { du: "Ordne zu!", ihr: "Ordnet zu!" },
                example_de: [{ "text": "Ordnen Sie", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "zu", "kasus": "verb" }, { "text": ".", "kasus": "none" }],
                example_en: "Match.",
                cloze_parts: ["", " Sie ", "."],
                cloze_answers: ["Ordnen", "zu"]
            },
            {
                id: "lernen-sprachenlernen-018",
                wortart: "Verb",
                german: "ankreuzen",
                english: "to tick / to mark with a cross",
                trennbar: true,
                hilfsverb_perfekt: "haben",
                partizip_ii: "angekreuzt",
                konjugation_praesens: { ich: "kreuze an", du: "kreuzt an", er_sie_es: "kreuzt an", wir: "kreuzen an", ihr: "kreuzt an", sie_Sie: "kreuzen an" },
                imperativ: { du: "Kreuz an!", ihr: "Kreuzt an!" },
                example_de: [{ "text": "Kreuzen Sie", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "bitte", "kasus": "none" }, { "text": " ", "kasus": "none" }, { "text": "an", "kasus": "verb" }, { "text": ".", "kasus": "none" }],
                example_en: "Please tick.",
                cloze_parts: ["", " Sie bitte ", "."],
                cloze_answers: ["Kreuzen", "an"]
            }
        ],

        // --- NEUE KATEGORIE 4: Konzepte & Prüfung ---
        "Konzepte & Prüfung": [
            {
                id: "lernen-sprachenlernen-011",
                wortart: "Nomen",
                german: "Beispiel",
                artikel: "das",
                plural: "Beispiele",
                english: "example",
                example_de: [{ "text": "Kannst", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "du", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "ein Beispiel", "kasus": "akkusativ" }, { "text": " ", "kasus": "none" }, { "text": "geben", "kasus": "verb" }, { "text": "?", "kasus": "none" }],
                example_en: "Can you give an example?",
                cloze_parts: ["Kannst du ein ", " geben?"],
                cloze_answers: ["Beispiel"]
            },
            {
                id: "lernen-sprachenlernen-012",
                wortart: "Nomen",
                german: "Fehler",
                artikel: "der",
                plural: "Fehler",
                english: "mistake / error",
                example_de: [{ "text": "Ich", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "hatte", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "vier Fehler", "kasus": "akkusativ" }, { "text": " ", "kasus": "none" }, { "text": "in der Englischarbeit", "kasus": "dativ" }, { "text": ".", "kasus": "none" }],
                example_en: "I had four mistakes in the English test.",
                cloze_parts: ["Ich hatte vier ", " in der Englischarbeit."],
                cloze_answers: ["Fehler"]
            },
            {
                id: "lernen-sprachenlernen-013",
                wortart: "Adjektiv",
                german: "richtig",
                english: "correct / right",
                example_de: [{ "text": "Das", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "ist", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "richtig", "kasus": "none" }, { "text": ".", "kasus": "none" }],
                example_en: "That is correct.",
                cloze_parts: ["Das ist ", "."],
                cloze_answers: ["richtig"]
            },
            {
                id: "lernen-sprachenlernen-014",
                wortart: "Adjektiv",
                german: "falsch",
                english: "wrong / false",
                example_de: [{ "text": "Das", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "ist", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "falsch", "kasus": "none" }, { "text": ".", "kasus": "none" }],
                example_en: "That is wrong.",
                cloze_parts: ["Das ist ", "."],
                cloze_answers: ["falsch"]
            },
            {
                id: "lernen-sprachenlernen-019",
                wortart: "Nomen",
                german: "Lösung",
                artikel: "die",
                plural: "Lösungen",
                english: "solution / answer",
                example_de: [{ "text": "Die Lösung", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "ist", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "richtig", "kasus": "none" }, { "text": ".", "kasus": "none" }],
                example_en: "The solution is correct.",
                cloze_parts: ["Die ", " ist richtig."],
                cloze_answers: ["Lösung"]
            },
            {
                id: "lernen-sprachenlernen-020",
                wortart: "Nomen",
                german: "Text",
                artikel: "der",
                plural: "Texte",
                english: "text",
                example_de: [{ "text": "Der Text", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "ist", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "lang", "kasus": "none" }, { "text": ".", "kasus": "none" }],
                example_en: "The text is long.",
                cloze_parts: ["Der ", " ist lang."],
                cloze_answers: ["Text"]
            },
            {
                id: "lernen-sprachenlernen-021",
                wortart: "Nomen",
                german: "Teil",
                artikel: "der",
                plural: "Teile",
                english: "part",
                example_de: [{ "text": "Der erste Teil", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "ist", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "einfach", "kasus": "none" }, { "text": ".", "kasus": "none" }],
                example_en: "The first part is easy.",
                cloze_parts: ["Der erste ", " ist einfach."],
                cloze_answers: ["Teil"]
            },
            {
                id: "lernen-pruefungen-001",
                wortart: "Nomen",
                german: "Prüfung",
                artikel: "die",
                plural: "Prüfungen",
                english: "exam / test",
                example_de: [{ "text": "Die Prüfung", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "war", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "schwer", "kasus": "none" }, { "text": ".", "kasus": "none" }],
                example_en: "The exam was difficult.",
                cloze_parts: ["Die ", " war schwer."],
                cloze_answers: ["Prüfung"]
            },
            {
                id: "lernen-pruefungen-002",
                wortart: "Nomen",
                german: "Test",
                artikel: "der",
                plural: "Tests",
                english: "test",
                example_de: [{ "text": "Wir", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "schreiben", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "einen Test", "kasus": "akkusativ" }, { "text": ".", "kasus": "none" }],
                example_en: "We are writing a test.",
                cloze_parts: ["Wir schreiben einen ", "."],
                cloze_answers: ["Test"]
            },
            {
                id: "lernen-pruefungen-003",
                wortart: "Nomen",
                german: "Note",
                artikel: "die",
                plural: "Noten",
                english: "grade / mark",
                example_de: [{ "text": "In Englisch", "kasus": "dativ" }, { "text": " ", "kasus": "none" }, { "text": "habe", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "ich", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "eine Eins", "kasus": "akkusativ" }, { "text": ".", "kasus": "none" }],
                example_en: "I have an A (a one) in English.",
                cloze_parts: ["In Englisch habe ich eine ", "."],
                cloze_answers: ["Eins"]
            },
            {
                id: "lernen-pruefungen-004",
                wortart: "Nomen",
                german: "Punkt",
                artikel: "der",
                plural: "Punkte",
                english: "point",
                example_de: [{ "text": "Wir", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "haben", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "zehn Punkte", "kasus": "akkusativ" }, { "text": ".", "kasus": "none" }],
                example_en: "We have ten points.",
                cloze_parts: ["Wir haben zehn ", "."],
                cloze_answers: ["Punkte"]
            },
            {
                id: "lernen-pruefungen-005",
                wortart: "Verb",
                german: "bestehen",
                english: "to pass (an exam)",
                trennbar: false,
                hilfsverb_perfekt: "haben",
                partizip_ii: "bestanden",
                konjugation_praesens: { ich: "bestehe", du: "bestehst", er_sie_es: "besteht", wir: "bestehen", ihr: "besteht", sie_Sie: "bestehen" },
                imperativ: { du: "Besteh!", ihr: "Besteht!" },
                example_de: [{ "text": "Ich", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "habe", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "die Prüfung", "kasus": "akkusativ" }, { "text": " ", "kasus": "none" }, { "text": "bestanden", "kasus": "verb" }, { "text": ".", "kasus": "none" }],
                example_en: "I have passed the exam.",
                cloze_parts: ["Ich habe die Prüfung ", "."],
                cloze_answers: ["bestanden"]
            },
            {
                id: "lernen-pruefungen-006",
                wortart: "Nomen",
                german: "Antwortbogen",
                artikel: "der",
                plural: "Antwortbögen",
                english: "answer sheet",
                example_de: [{ "text": "Bitte", "kasus": "none" }, { "text": " ", "kasus": "none" }, { "text": "geben Sie", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "den Antwortbogen", "kasus": "akkusativ" }, { "text": " ", "kasus": "none" }, { "text": "ab", "kasus": "verb" }, { "text": ".", "kasus": "none" }],
                example_en: "Please hand in the answer sheet.",
                cloze_parts: ["Bitte geben Sie den ", " ab."],
                cloze_answers: ["Antwortbogen"]
            },
            {
                id: "lernen-pruefungen-007",
                wortart: "Nomen",
                german: "Ergebnis",
                artikel: "das",
                plural: "Ergebnisse",
                english: "result",
                example_de: [{ "text": "Das Ergebnis", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "ist", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "gut", "kasus": "none" }, { "text": ".", "kasus": "none" }],
                example_en: "The result is good.",
                cloze_parts: ["Das ", " ist gut."],
                cloze_answers: ["Ergebnis"]
            },
            {
                id: "lernen-pruefungen-008",
                wortart: "Verb",
                german: "kontrollieren",
                english: "to check / to control",
                trennbar: false,
                hilfsverb_perfekt: "haben",
                partizip_ii: "kontrolliert",
                konjugation_praesens: { ich: "kontrolliere", du: "kontrollierst", er_sie_es: "kontrolliert", wir: "kontrollieren", ihr: "kontrolliert", sie_Sie: "kontrollieren" },
                imperativ: { du: "Kontrollier!", ihr: "Kontrolliert!" },
                example_de: [{ "text": "Der Lehrer", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "kontrolliert", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "die Hausaufgaben", "kasus": "akkusativ" }, { "text": ".", "kasus": "none" }],
                example_en: "The teacher checks the homework.",
                cloze_parts: ["Der Lehrer ", " die Hausaufgaben."],
                cloze_answers: ["kontrolliert"]
            },
            {
                id: "lernen-pruefungen-009",
                wortart: "Phrase",
                german: "fertig sein",
                english: "to be ready / to be finished",
                example_de: [{ "text": "Ich", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "bin", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "schon", "kasus": "none" }, { "text": " ", "kasus": "none" }, { "text": "fertig", "kasus": "none" }, { "text": ".", "kasus": "none" }],
                example_en: "I am already finished.",
                cloze_parts: ["Ich bin schon ", "."],
                cloze_answers: ["fertig"]
            },
            {
                id: "lernen-pruefungen-010",
                wortart: "Adjektiv",
                german: "schwierig",
                english: "difficult",
                example_de: [{ "text": "Die Aufgabe", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "ist", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "schwierig", "kasus": "none" }, { "text": ".", "kasus": "none" }],
                example_en: "The task is difficult.",
                cloze_parts: ["Die Aufgabe ist ", "."],
                cloze_answers: ["schwierig"]
            },
            {
                id: "lernen-pruefungen-011",
                wortart: "Adjektiv",
                german: "einfach",
                english: "easy / simple",
                example_de: [{ "text": "Die Übung", "kasus": "nominativ" }, { "text": " ", "kasus": "none" }, { "text": "ist", "kasus": "verb" }, { "text": " ", "kasus": "none" }, { "text": "ganz einfach", "kasus": "none" }, { "text": ".", "kasus": "none" }],
                example_en: "The exercise is very easy.",
                cloze_parts: ["Die Übung ist ganz ", "."],
                cloze_answers: ["einfach"]
            }
        ]
    }
};